### ISSUE TITLE
Support rustls (instead of OpenSSL)

### ISSUE THREAD

**Issue by orhun** [cargo-generate/cargo-generate#1008]
Hey! 🐻 

For the context, I'm coming here from https://github.com/shuttle-hq/shuttle/issues/100

I don't know if it is possible to use `rustls` for `cargo-generate` but wanted to bring this issue to your attention.

Would it be feasible to support `rustls`?

**Comment by sassman** [comment]
Hey @orhun,

BTW very cool that you work now on shuttle!

> Would it be feasible to support rustls?

The Question would be does `git2` support rustls instead? Because cargo-generate pulls this very dependency to openssl from `git2` as you can see here:

https://github.com/cargo-generate/cargo-generate/blob/b9f9b438e0b4d1cd8171da39fb897b583643e82d/Cargo.toml#L75

**Comment by orhun** [comment]
Hey Sven!

> BTW very cool that you work now on shuttle!

Thank you! 🚀🚀🚀 

> The Question would be does git2 support rustls instead?

Ah I see, then I need to go one layer deeper.

⛏️ https://github.com/rust-lang/git2-rs/issues/623

BTW are there plans to switch to `gitoxide` in the future?

**Comment by sassman** [comment]
For some features we use gitoxide already. E.g gitconfig parsing etc.

But I watch the progress on gitoxide and at some point I have high hopes to be able to switch over. So yes there are plans :)

**Comment by orhun** [comment]
Great news, so it is possible to get rid of OpenSSL in the feature, nice! 🐻

**Comment by sassman** [comment]
will close this for now, and keep the tracking issue #1037 instead.

**Comment by sassman** [comment]
just in case, good news: with v0.24.0 we will ship gix as backend, that means rustls by default and no more openssl issues.
