### ISSUE TITLE
break up tests into separate files

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#107]
the time has come. the test file is too long. i'd like to see it separated out by category- similar to how our src dir is broken up.

**Comment by k0pernicus** [comment]
If nobody wants to work on... I can work on it this week-end :)

**Comment by ashleygwilliams** [comment]
i doubt i'll get to it- so go for it! thanks :)

**Comment by sassman** [comment]
I believe we made some improvements here. 
So for now I'll close it. Feel free to open specific issues for portions that needs more love.
