### ISSUE TITLE
default values from the `cargo-generate.toml` when `silent == true` are not in case they are not defined

### ISSUE THREAD

**Issue by Andrew15-5** [cargo-generate/cargo-generate#1114]
After trying to create a cargo project from a template that have default values, it looks like `cargo-generate` doesn't support automatic usage of the default values, instead you have to provide all values manually (via `define`). The issue is the same with CLI and library API.

I tried running `cargo generate 'dioxuslabs/dioxus-template' -n name -s -d platform=web`, which prints:
```
⚠️   Favorite `dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
🔧   platform: "web" (variable provided via CLI)
🔧   Destination: /tmp/name ...
🔧   project-name: name ...
🔧   Generating template ...
Error: variable `router` was missing in config file running on silent mode
```

But in the config there is:

```toml
[placeholders.router]
type = "bool"
prompt = "Should the application use the dioxus router?"
default = true
```

which means that the program simply doesn't support or doesn't see the default values. If I then run `cargo generate 'dioxuslabs/dioxus-template' -n name -s -d platform=web -d router=true` it gives me:

```
⚠️   Favorite `dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
🔧   platform: "web" (variable provided via CLI)
🔧   router: "true" (variable provided via CLI)
🔧   Destination: /tmp/name ...
🔧   project-name: name ...
🔧   Generating template ...
Error: variable `styling` was missing in config file running on silent mode
```

But in the config there is:

```toml
[conditional.'platform == "web"'.placeholders.styling]
type = "string"
prompt = "How do you want to create CSS?"
choices = ["Tailwind", "Vanilla"]
default = "Vanilla"
```

So in order to create the project, I have to specify all the necessary options/variables:

```sh
cargo generate 'dioxuslabs/dioxus-template' -n name -s -d platform=web -d router=true -d styling=Vanilla
```

<details><summary>output</summary>

```
⚠️   Favorite `dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
🔧   platform: "web" (variable provided via CLI)
🔧   router: "true" (variable provided via CLI)
🔧   styling: "Vanilla" (variable provided via CLI)
🔧   Destination: /tmp/name ...
🔧   project-name: name ...
🔧   Generating template ...
🔧   Moving generated files into: `/tmp/name`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /tmp/name
```

</details>

Which could've been avoided if the program can grab the default values from the config file. I'm fairly new to this, so I'm not 100% sure there is no solution already, but it seems like there isn't one yet.

I don't know, maybe there should be another flag besides the `silent` that will only responsible for extracting the default values when `silent` is used. Maybe `use-default-values` or something.

**Comment by sassman** [comment]
I see. 

It's right, the default values should take place if there are missing defined values.

**Comment by Andrew15-5** [comment]
I fixed it and here is the output:

```sh
cargo-generate generate -s -n project -d platform=web gh:dioxuslabs/dioxus-template
```

```
⚠️   Favorite `gh:dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
🔧   platform: "web" (value from CLI)
🔧   Destination: /tmp/project ...
🔧   project-name: project ...
🔧   Generating template ...
🔧   router: "true" (default value from template)
🔧   styling: "Vanilla" (default value from template)
🔧   Moving generated files into: `/tmp/project`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /tmp/project
```

![image](https://github.com/cargo-generate/cargo-generate/assets/37143421/efc24f24-a4f5-45ff-b1cc-0b772d0dc875)

I will open a PR shortly. The main question is how soon it can be merged and a new version with the fix published to the crates.io? Well, at least the first one, because you can lock a hash for the dependency, but using version instead of a hash would be, of course, better.
