### ISSUE TITLE
Unable to cargo install cargo-generate

### ISSUE THREAD

**Issue by pranavdesai-cdcx** [cargo-generate/cargo-generate#1127]
**Describe the bug**
unable to install cargo-generate, need help

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [ ] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [ ] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo install cargo-generate`

error : Caused by:
  [56] Failure when receiving data from the peer (Recv failure: Connection reset by peer)
  
**Screenshots**
![image](https://github.com/cargo-generate/cargo-generate/assets/159907384/76cd26f6-7cee-4564-bcd5-899d2dcbcd64)
**Desktop (please complete the following information):**
 - OS: [macOs]
 - Version: [14.13.1]
 - Shell: [zsh]
 - `rustc --version`: rustc 1.76.0 (07dca489a 2024-02-04)

**Additional context**

**Comment by sassman** [comment]
I guess the upcoming version will fix it.

Meanwhile you can give an installation via `cargo install --locked cargo-generate` a try.
