### ISSUE TITLE
Error installing from libgit2-sys, but resolved. 

### ISSUE THREAD

**Issue by jjgonecrypto** [cargo-generate/cargo-generate#113]
I had an issue trying to run `cargo install cargo-generate` on a new MBP on OS X 10.14 (Mojave). 

I was seeing the following: 

```
...
cargo:warning=/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
cargo:warning=        lzma_bool reserved_bool3;
cargo:warning=        ^
cargo:warning=fatal error: too many errors emitted, stopping now [-ferror-limit=]
cargo:warning=20 errors generated.
exit code: 1

--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
```

After a bunch of digging into `libgit2-sys`, it turned out the issue was that faulty `block.h` header file in my `/usr/local/include` folder. `brew doctor` brought up the issue (along with a bunch of other files) and after removing that file myself, I was unblocked.

Just adding this here for posterity.

**Comment by sjuanman** [comment]
I had the same problem and your solution also worked for me.

Thank you!
