### ISSUE TITLE
Don't rename underscores to hyphens in project names

### ISSUE THREAD

**Issue by Timmmm** [cargo-generate/cargo-generate#1152]
`cargo-generate` swaps underscores to hyphens in project names:

```
🤷   Project Name: lock_firmware
⚠️   Renaming project called `lock_firmware` to `lock-firmware`...
```

I'm not aware of any requirement that Rust projects use hyphens, so this seems unnecessary and unwelcome.

In my opinion it's preferable to use underscores so that the crate name matches the name you use in Rust code. I lost an hour of my life to that paper cut once.

**Comment by sassman** [comment]
That's actually a fair point. Underscore to dash is not necessary. Dash to underscore is necessary on the module level.

I will prepare a fix.
