### ISSUE TITLE
cargo generate --git generates project folder but not the project itself

### ISSUE THREAD

**Issue by azami63** [cargo-generate/cargo-generate#1155]
**Describe the bug**
cargo generate --git https://github.com/azami63/wasm-pack-template
🤷   Project Name: guest-wasm
🔧   Destination: /Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm ...
🔧   project-name: guest-wasm ...
🔧   Generating template ...
🔧   Moving generated files into: `/Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm

**make sure you**
- [ 1.76.0] I'm on the latest rust version `rustup update`
- [ 0.19.0] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [ N/A] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo generate <--git https://github.com/azami63/wasm-pack-template>`
2. output it generated..
3. 🤷   Project Name: guest-wasm
🔧   Destination: /Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm ...
🔧   project-name: guest-wasm ...
🔧   Generating template ...
🔧   Moving generated files into: `/Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm
4. See error: not error issued!

**Expected behavior**
there are no files generated in guest-was project folder, that is , the generated rust files: cargo.toml, src folder ; don't exist in the folder!!
I used a pre-existed template <wasm-pack-template> 
**Screenshots**
🤷   Project Name: guest-wasm
🔧   Destination: /Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm ...
🔧   project-name: guest-wasm ...
🔧   Generating template ...
🔧   Moving generated files into: `/Users/sohrabazamighadim/Projects/EMSCRIPTEN/RUST+WEBASSEMBLY-COMPONENT-MODEL+WASM+WASI/guest-wasm`...
🔧   Initializing a fresh Git repository
✨   Done! New project created <.../abosulte path>/guest-wasm

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS | Linux | Windows]
 - Version: [big sure 11.7.10]
 - Build tools: [visual code  |cargo generate | cargo]
 - Shell: [terminal | zsh | bash]
 - `rustc --version`: 1.76.0
 - `cargo generate --version`: 0.19.0

**Additional context**

	ui = auto
[user]
	name = sohrab
	email = azamighadim2@gmail.com
[pull]
	rebase = true
[init]
	defaultBranch = main
[safe]
	directory = /workspace
	directory = /workspace

**Comment by azami63** [comment]
I have spend 2 days on this issue and could not fix it. I appreciate your help Sheryl William.

BR
sag

**Comment by sassman** [comment]
@azami63, only by looking at your template: https://github.com/azami63/wasm-pack-template

I must say cargo-generate does all things right. 
You may ask why now? 
Well, your template repo is in fact empty, it contains only 3 files, and not rust code at all.

<img width="315" alt="image" src="https://github.com/cargo-generate/cargo-generate/assets/329682/2d56d4f2-e466-47c7-89c6-31f0bb50e2e1">
