### ISSUE TITLE
Tag flag no longer working as expected.

### ISSUE THREAD

**Issue by JaatadiaMulesoft** [cargo-generate/cargo-generate#1222]
**Describe the bug**
Backwards breaking change was introduced in in v0.21.2, specifying the tag flag no longer works.

**To Reproduce**
1. ` cargo generate --name my-expanded-template https://github.com/cargo-generate/cargo-generate.git --tag v0.19.0 -d license=none example-templates/hooks`
2. `Error: revspec 'v0.19.0' not found; class=Reference (4); code=NotFound (-3)

Stack backtrace:
   0: std::backtrace::Backtrace::capture
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: cargo_generate::git::utils::clone_git_template_into_temp
   3: cargo_generate::generate
   4: cargo_generate::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: _main`

**Expected behavior**
This should continue working as it did with v0.21.1

**Screenshots**
<img width="1247" alt="image" src="https://github.com/cargo-generate/cargo-generate/assets/35300185/18907f3e-9641-446f-a46f-f88cca14a5b4">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma 14.5
 - Build tools: [e.g. msvc | gnu | gcc]
 - Shell: zsh
 - `rustc --version`:  1.74.0
 - `cargo generate --version`:  v0.21.2

**Additional context**

My guess is that when setting the [depth to 1](https://github.com/cargo-generate/cargo-generate/commit/fd006cd2da1f22643fa6e9751f0f2942669569fe) the tag information is no longer being fetched.

**Comment by sassman** [comment]
It's going to be fixed in `v0.21.3` which is about to be released. CI started already.
