### ISSUE TITLE
Implicit `.liquid` matching in `template.ignore` 

### ISSUE THREAD

**Issue by gibbz00** [cargo-generate/cargo-generate#1294]
I have a template repo with multiple files that have generated counterpart of the same name:

```
a.toml
README.md
README.md.liquid
cargo-generate.toml
```
```toml
# cargo-generate.toml
[template]
ignore = [
  "README.md"
]
````

Which results in the following after running `cargo-generate` (v. 0.22.0):

```
a.toml
.git
```

My expectation was that only `README.md.liquid` would remain. This time with its template fields expanded, and the `.liquid` extension stripped.

I may work around this using some Rhai post-hooks, but I would like to know if there's a better way to go about it.

#### Update

Having looked into the source code a bit, it seems as if extension stripping is done before template expansion, and that stripping should override any pre-existing file of the same name. Removing `README.md` from ignore does not seem to fix it though. The file is left as is, without the contents from the `.liquid` file.

#### Update 2

I tried to reproduce this in some integration tests, but they seem to pass without any problems, https://github.com/cargo-generate/cargo-generate/commit/5a45c7f646acfaf33d8e55e50a92846c1ab0c16f.

**Comment by sassman** [comment]
That is an interesting case, I agree with your expectation of 

- the `README.md.liquid` should be used to
- replace the `README.md` 
- and **no** `README.md` must be on the ignore list

Do you have the repo already somewhere available?
Otherwise I might reuse your integration test.

**Comment by gibbz00** [comment]
No sure why removing the respective files from the ignore list didn't seem fix things at first, but now it does 😅  

Could technically close this issue here and now. But maybe it would be better if it is closed together with the merging of a PR that includes the integration tests and some documentation that clarifies this behavior?

**Comment by sassman** [comment]
Thanks for the PR that improves the clarity and tests.
