### ISSUE TITLE
Does not compile on Fedora 41 due to OpenSSL not being present

### ISSUE THREAD

**Issue by abergmeier** [cargo-generate/cargo-generate#1318]
**Describe the bug**
It seems like generate has a dependency on OpenSSL. In todays OS landscape chances are quite good that OpenSSL will be no longer available on systems. Thus it would be good to detect whichever SSL library is present on the system and use that.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `cargo install cargo-generate`

**Expected behavior**
It should not fail to install.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Fedora 41
 - Build tools: gcc
 
** Output **

```
warning: openssl-sys@0.9.104: Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the compilation process. See stderr section below for further information.
```

**Comment by sassman** [comment]
Have you also already tried the vendored version?

```
cargo install cargo-generate --features vendored-openssl
```

**Comment by abergmeier** [comment]
Yeah - problem was actually that I did not have `openssl-devel` installed.
