### ISSUE TITLE
Allow template initialization in place

### ISSUE THREAD

**Issue by armandas** [cargo-generate/cargo-generate#1326]
What do you think about adding a flag that would allow initializing the project inside the template directory (i.e. overwrite template files)?

I see two use cases for this:

- CI of template repositories would be simplified greatly
- Users could initialize the project after creating a repository from the GitHub template

**Comment by jaredwy** [comment]
Doesn't the `--init` flag do this?

**Comment by armandas** [comment]
No, from the docs:

> NOTE: cargo-generate will not allow any existing files to be overwritten and will fail to generate any files should there be any conflicts.

**Comment by sassman** [comment]
the `--init` flag in combination with `--overwrite` should support your use case.

**Comment by armandas** [comment]
@sassman Thanks, I missed the `--overwrite` flag.
