### ISSUE TITLE
cargo generate output      unexpected EOF; class=Http (34)

### ISSUE THREAD

**Issue by qiaopengjun5162** [cargo-generate/cargo-generate#1328]
**Describe the bug**
cargo generate output      unexpected EOF; class=Http (34)

<img width="1616" alt="image" src="https://github.com/user-attachments/assets/d6073797-2f94-4b14-ac4f-8e90808783b8">

rustc -V
rustc 1.83.0 (90b35a623 2024-11-26)

**Comment by sassman** [comment]
The GitHub org and repo you're using does not exist.

**Comment by sassman** [comment]
This is then a duplicate of #1278

**Comment by qiaopengjun5162** [comment]
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/f0942aa2-c1e1-4bc1-ac4b-9fa6d2ea2229">
Does this GitHub repository exist or report an error?

**Comment by qiaopengjun5162** [comment]
use ssh solve this problem
