### ISSUE TITLE
enabling redirection in cargo gen

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#138]
as per https://github.com/ashleygwilliams/cargo-generate/issues/128#issuecomment-443334684

**Comment by DD5HT** [comment]
#67 would solve this issue too.

**Comment by sassman** [comment]
as for today (`v0.12.0`) we have shortcuts and prefixes like `gh-user/repo` or `gh:user/repo` for valid repository urls. 
Nobody needs to type any full urls anymore. Hence I think we are past this problem here.
