### ISSUE TITLE
move to azure pipelines

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#152]

**Comment by xoac** [comment]
I am working on ready to use template for rust + azure pipelines. Maybe you will be interested. Look [here](https://github.com/xoac/rust-azure-pipelines)

**Comment by MarcoIeni** [comment]
Is this issue still valid or maybe should we prefer github actions now?

**Comment by xoac** [comment]
In my opinion you should use github acttions. [Here is example](https://github.com/xoac/crates-io-lib-template/blob/master/.github/workflows/main.yml) that should work out of the box.

**Comment by MarcoIeni** [comment]
I work on moving to GitHub actions, if maintainers agree this is needed.

**Comment by sassman** [comment]
I think we can close this, since now all is migrated to GitHub actions and working quite fine.
