### ISSUE TITLE
Can dir names and file names be templated?

### ISSUE THREAD

**Issue by kitsuneninetails** [cargo-generate/cargo-generate#159]
Can I have a file like `test_{{project-name}}.rs` and have that convert during generation to `test_my-project.rs`?

If not, that's something that probably needs to be added IMHO to give this any real utility over and above a simple `find . -type f -exec sed -ie "s/{{project-name}}/$1/g" {} \;`

Changing dir names and file names based off templates is much harder and a more interesting/helpful problem to solve IMHO.  It'd be nice if this could do that.

**Comment by k0pernicus** [comment]
I think we can include this feature, as the program iterates on each file of the template project.
We just need to include a check on each file entry [here](https://github.com/ashleygwilliams/cargo-generate/blob/54a85ed98ee4ad06c8228dd60ac070ff483291dd/src/template.rs#L102).

**Comment by k0pernicus** [comment]
@kitsuneninetails I am writing a feature request for your demand - I wrote the code and the tests and both work.
I will clean the code, and try a PR soon.

**Comment by xortive** [comment]
https://github.com/ashleygwilliams/cargo-generate/pull/161 was going to solve this for 0.4.0, but it's being pushed back to a later release. https://github.com/ashleygwilliams/cargo-generate/pull/182 has some more details on the motivation behind this.

**Comment by jmjoy** [comment]
Need this feature too!

**Comment by Michael-F-Bryan** [comment]
I can think of a couple use cases where I'd like this, for example creating a template for a workspace where there's a `{{project_name}}` crate at the project root.

Is there anything I can do to help with the implementation or testing?

**Comment by k0pernicus** [comment]
Hi @Michael-F-Bryan , you can take a look at how I proposed it a loooong time ago (https://github.com/ashleygwilliams/cargo-generate/pull/161) and propose a solution to solve the issue from @xortive at this time (see #182 for the motivation behind the revert at this time).

**Comment by taurr** [comment]
#255 also relates to this!

**Comment by notdanilo** [comment]
Is there any progress being made for this issue?

**Comment by csarn** [comment]
I am also interested in this feature. Python's "cookiecutter" does that, too.

**Comment by sassman** [comment]
solved with #386 and released in v0.8.0
