### ISSUE TITLE
Pre/Post Hooks

### ISSUE THREAD

**Issue by epage** [cargo-generate/cargo-generate#18]
This is something else that has been handy from [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html) but is more questionable due to security.

Use cases from my python cookiecutter translated to Rust.
- Custom SCM support
- Verifying ident (see #17)
- `cargo update && git add Cargo.lock` for bins

The main question is how would we handle this in Rust?
- shell scripts aren't portable
- `cargo-script`?

To alleviate security concerns, we could have flags for
- Showing what will be done to the system (prints the scripts)
- Runs the template but not the hooks (requiring manual intervention)

**Comment by MarcoIeni** [comment]
I did a little research of what projects allow to run rust code. Here is what I found:
- https://crates.io/crates/rust-script
- https://crates.io/crates/cargo-play
- https://crates.io/crates/runner
- https://crates.io/crates/cargo-eval (fork of cargo-script which wasn't updated in 4 years)
