### ISSUE TITLE
cargo-generate fails to clone git repository when run from Linux Docker container on Windows host

### ISSUE THREAD

**Issue by ZenoArrow** [cargo-generate/cargo-generate#221]
Version numbers for key system components:
* Windows 10 x64 (Version 1909, OS Build 18363.778)
* Docker Desktop 2.2.0.5 (N.B. Using Linux containers rather than Windows containers)
* PowerShell 7.0.0.0
* rustc 1.42.0 (b8cedc004 2020-03-09)
* cargo 1.42.0 (86334295e 2020-01-31)
* wasm-pack 0.9.1
* cargo-generate 0.5.0

After installing Docker Desktop and PowerShell, the following list of commands are run in PowerShell before the error is returned...
PS C:\PersonalProjects\RustProjects>
	docker run -e USER=MyUserAccount -it -v "$(pwd):/usr/src" -w /usr/src rust:latest
	cargo install wasm-pack
	cargo install cargo-generate
	wasm-pack new hello-wasm --template https://github.com/rustwasm/wasm-pack-template --mode normal

Returned error message:
	Generating a new rustwasm project with name 'hello-wasm'...
	Creating project called `hello-wasm`...
	warning: spurious network error (2 tries remaining): failed to truncate pack file '/usr/src/hello-wasmiYz3Rx/objects/pack/pack_git2_AEBjQf': Operation not permitted; class=Os (2)
	warning: spurious network error (1 tries remaining): failed to truncate pack file '/usr/src/hello-wasmiYz3Rx/objects/pack/pack_git2_vH1RL3': Operation not permitted; class=Os (2)
	Error:  Git Error: failed to clone into: /usr/src/hello-wasmiYz3Rx
	Error: Running cargo-generate
	Caused by: failed to execute `cargo-generate`: exited with exit code: 1
	  full command: "/usr/local/cargo/bin/cargo-generate" "generate" "--git" "https://github.com/rustwasm/wasm-pack-template" "--name" "hello-wasm"

Worth noting that I get the same error when running cargo-generate directly, rather than indirectly through wasm-pack, i.e. I get the same error when running the following command:

`"/usr/local/cargo/bin/cargo-generate" "generate" "--git" "https://github.com/rustwasm/wasm-pack-template" "--name" "hello-wasm"
`

Also odd that the folder that is attempted to be used as the destination of the clone includes seemingly random text, i.e. instead of cloning into /usr/src/hello-wasm in the example above, it tried to clone into /usr/src/hello-wasmiYz3Rx instead.

Also worth noting that if I git clone the rustwasm/wasm-pack-template repo directly within the same Docker container it seems to work without any issues, i.e. the following works fine:

`git clone https://github.com/rustwasm/wasm-pack-template`

I'm hoping I've provided enough information to help replicate the fault, but if there's anything else I can do to help please let me know.

**Comment by k0pernicus** [comment]
Hi @ZenoArrow,

Do you still have this issue?

Concerning your comment here:
> Also odd that the folder that is attempted to be used as the destination of the clone includes seemingly random text, i.e. instead of cloning into /usr/src/hello-wasm in the example above, it tried to clone into /usr/src/hello-wasmiYz3Rx instead.

cargo-generate will clone the project in a "dummy" project name, and make some process, before moving the generated project in the destination (and remove the older project).

About your issue, I think it is related to https://github.com/rust-lang/cargo/issues/6652, no?

**Comment by sassman** [comment]
It's very likely to be a windows / network-filesystem issue. If the issue persists feel free to reopen.
