### ISSUE TITLE
cli option for passing the project description in

### ISSUE THREAD

**Issue by sassman** [cargo-generate/cargo-generate#226]
I was thinking the `Cargo.toml` has this field `description` and often this description is then placed in the README.md and so on. 

So maybe it makes sense to extend the cli paramters in the same fashion as `name` works just for `description`, means if omitted the cli interactively asks for the project description. 

I have already a draft implementation that will follow soon to illustrate the thing.
Of course, I'm thankful for any feedback about this idea.

**Comment by k0pernicus** [comment]
Hi @sassman

So, if I understood the request, you want to add a `description` field in the CLI to fill (and/or override?) the `description` key in Cargo.toml, that's right?

**Comment by sassman** [comment]
Hi @k0pernicus,

basically yes. The `description` variable then can be used as you said in the `Cargo.toml` but also in the Readme. It does not really matter, it's just yet another template variable.

Actually I was thinking of it a bit further, there are use cases where even more variables are super helpful. So to generify this idea here, I wanted to propose a config file, named for examples `.cargo-generate.toml` that exists in the git repo that is the template for a new project. In this config file we can specify the additional variables that this very template needs to have filled out in order to be complete. For example:

```
description = "Description is used in Cargo.toml and the README.md"
category = "Category is used in Cargo.toml for publishing on crates.io" 
```

So, here in this config file we have 2 variables (description, category) with a verbose text assigned. 
When we run now `cargo generate --git https://my-template-with-config-file` then it will parse the config file and will promt for every variable that is defined inside, with the description text that is assigned. 
So that I can enter those variables and cargo-generate then has more variables that will be replaced.

Hope that is explained well enough, let's maybe discuss the pros and cons.

**Comment by MarcoIeni** [comment]
sassman, basically I think you are proposing custom variables, which is a feature I would really like, too, but if that's the case this issue is a duplicate of https://github.com/ashleygwilliams/cargo-generate/issues/17 .
If you agree you can close this.

**Comment by sassman** [comment]
not more needed, because of custom variables.
