### ISSUE TITLE
New git-related variables

### ISSUE THREAD

**Issue by SirWindfield** [cargo-generate/cargo-generate#229]
It would be nice if you could provide git-related variables for the template. I was mainly thinking about the default `user.name` one. This would allow templates to use that name for license files instead of the cargo author field (`{{ authors[0] }}`). The cargo field does, in almost all cases, also include the E-Mail address. `git_name` wouldn't.

**Comment by MarcoIeni** [comment]
duplicate of #163 
There is already an open pull request here: #164

**Comment by sassman** [comment]
tracking issue is #163
