### ISSUE TITLE
Add option to disable git repo initialization

### ISSUE THREAD

**Issue by avrong** [cargo-generate/cargo-generate#244]
It can work similarly to `--vcs none` in Cargo in, except here it should be contrasted from `--git` option (describing the template repo url) in `new` (and `init` #193) commands and support only git/no-vcs states in the current implementation.

This would help with rustwasm/wasm-pack#901.

**Comment by taurr** [comment]
#290 disables git initialization when generating stuff within an existing repository - will it be enough, or will an actual option still be needed if/when it is merged?

I'd be happy to volunteer to implement it, though what should the option be called?

**Comment by sassman** [comment]
I guess this was more of a general feature request since cargo new behaves this way. For consistency reasons I think it makes sense.

Of course every contribution is warmly welcomed.

**Comment by taurr** [comment]
@sassman 
Maybe close this one?

**Comment by sassman** [comment]
This will be released with `0.6.0` (pretty soon) and can be tried out on master.
