### ISSUE TITLE
One-command template for feature-packed projects (wasm-js-template)

### ISSUE THREAD

**Issue by Mubbly** [cargo-generate/cargo-generate#247]
I created a template that packs many useful features (based on thesis research and analysis) without needing any prior dependencies or separate installations: **[wasm-js-template](https://github.com/Mubbly/wasm-js-template)**. 

Perhaps it could be included in [TEMPLATES.md](https://github.com/ashleygwilliams/cargo-generate/blob/master/TEMPLATES.md) - _"Generate feature-packed Rust/WebAssembly+JavaScript projects via one command"_

**Comment by sassman** [comment]
@Mubbly feel free to provide a PR for this. Useful templates are alway very appreciated.

**Comment by sassman** [comment]
@Mubbly I will close this one caused by inactivity, but feel free to submit a PR to include the suggested template.
