### ISSUE TITLE
A way to get the latest crates.io version of a dependency

### ISSUE THREAD

**Issue by toasteater** [cargo-generate/cargo-generate#249]
We have recently started working on a [template for the `godot-rust` project](https://github.com/godot-rust/godot-rust-template), and since we want to make releases more often in the future, it would be very convenient if we can make it so that the generated projects always depend on the latest version available at the time of generation, without having to manually provide patches to the template every time. As such, a way (filter?) to get the latest crates.io version of a dependency, optionally with a semver constraint, would be really great.

I'd imagine that this can be useful for projects that maintain "official" templates for their libraries, but perhaps it's too specific? I can make a PR for this if it's deemed useful.

**Comment by sassman** [comment]
Sounds like an nice feature. 
Just one thing that would be difficult to solve is, if your template contains code, that code depends of a very specific api of your dependent crate. When auto update to latest versions, the template code is not necessarily compatible to the api of the latest version of a particular crate. 
So eventually you would end up in updating your template anyways. 
So safer would be to write the cargo.toml of your template in a way to stick with a version like ` = 0.3` to receive always the latest version of a semantically compatible crate.

**Comment by toasteater** [comment]
> When auto update to latest versions, the template code is not necessarily compatible to the api of the latest version of a particular crate.
> So eventually you would end up in updating your template anyways.

I'm hoping that this would be possible to catch with some periodical CI, but yes, this is a valid concern for fast-moving crates. In our specific case, the template contains little code, and we don't expect the API to undergo large changes that require updates to it frequently, thus the original feature request.

I see that this might be a little too niche, so we'll stick to a normal Cargo.toml for now and see how it goes. Thanks for the response!

**Comment by taurr** [comment]
Why not just add the proper version pattern to cargo.toml then?

If it just uses 

```toml
[dependencies]
always-use-latest-crate = "*"
```

then a library will automatically be the latest released version. Support for locking by semantic versioning is built in, and compatibility is chosen entirely by the template author.

Then the user can always lock to specific desired versions that match the actual need.

**Comment by sassman** [comment]
I've tried to point out above that there are some potential footguns hidden:

> Just one thing that would be difficult to solve is, if your template contains code, that code depends of a very specific api of your dependent crate. When auto update to latest versions, the template code is not necessarily compatible to the api of the latest version of a particular crate.

for example your template depends on `clap` and the code is written with `clap = "0.2.*"`, and that works and compiles. When rewriting that dependency now as `clap = "*"` and meanwhile `clap` released a breaking version `1.0.0` or even `0.3.0` that slightly changes the api. This would then lead to the final project not compiling anymore and the uses would be pretty disappointed. 

That is why I'd recommend to pin-point down to the minor version, and letting the patch level at `*`. 

So there is no magic silver bullet when it comes to stay updated but also wanna be safe that things still work, either sacrificing stability for stayed at the latest versions or update. 

One suggestion would be to write a little PR bot that kicks in on release that opens a PR with version increments. Like it's possible for homebrew with a [github/workflow action](https://github.com/marketplace/actions/homebrew-bump-formula)

**Comment by sassman** [comment]
as for reasons given above I'm going to close this one.
