### ISSUE TITLE
support for global variables

### ISSUE THREAD

**Issue by macalimlim** [cargo-generate/cargo-generate#250]
support for global variables to be accessed in multiple files.

**Comment by MarcoIeni** [comment]
Can you explain this better? Maybe with an example? Thanks!

**Comment by macalimlim** [comment]
@MarcoIeni  Maybe have a `globals` file. In that file you can define global variables to be used in every file template. As an example of the use case for this is this [file](https://github.com/godot-rust/godot-rust-template/blob/master/Makefile) and this [file](https://github.com/godot-rust/godot-rust-template/blob/master/godot/export_presets.cfg). Both have common variable(s).

**Comment by taurr** [comment]
Actually, I will consider this a subset of (Custom variables. #17)

Should probably be marked duplicate!

**Comment by sassman** [comment]
global user defined global variables are supported not yet supported but the tracking issue is #17.

So I'm closing this one.
