### ISSUE TITLE
Shortcut name

### ISSUE THREAD

**Issue by sandmor** [cargo-generate/cargo-generate#256]
I want a manner to avoid copy-paste git URLs and instead of that specify an identifier, as the next example:
´´´
cargo generate orbtk
´´´

**Comment by MarcoIeni** [comment]
You can specify a git repo from GitHub in the format `owner/repository`.

For example
```
cargo generate --git rust-github/template
```

is the same of

```
cargo generate --git https://github.com/rust-github/template
```

Is this enough for you?

**Comment by sassman** [comment]
@taurr I'm currently checking your favourites feature and it's looking good so far. Let's move the discussion over to #210 since this issue is basically already implemented [since longer](https://github.com/cargo-generate/cargo-generate/commit/d2bb2e5e21eb650d1d2f9e9470921799c7ff3c72)
