### ISSUE TITLE
unable to generate a project when no master branch is present

### ISSUE THREAD

**Issue by macalimlim** [cargo-generate/cargo-generate#258]
why does cargo-generate need a master branch when generating from a project repository by using this command?

`cargo generate --git /path/to/git/template --name foo`

at this [PR](https://github.com/godot-rust/godot-rust-template/pull/23) for godot-rust-template, we would like to setup a test on the template where we could validate if the generated project could actually compile and run. Also please check the travis build [here](https://travis-ci.com/github/godot-rust/godot-rust-template/builds/199340921) for reference...

**Comment by MarcoIeni** [comment]
After #263 got merged, cargo generate looks by default for a `main` branch, too.
This is not released yet.

Anyway you can already specify a branch with the `--branch` flag.

Example:
`cargo generate --git https://github.com/rust-github/template --branch my-different-branch`

If you confirm that specifying the flag solves the issue for you, this issue could be closed when this feature is documented in the readme, I think.

**Comment by macalimlim** [comment]
@MarcoIeni  Hmmm, how would specifying a branch to the `cargo generate` command work on a PR scenario in travis?

**Comment by k0pernicus** [comment]
Hi,
@MarcoIeni has right: the current version of cargo-generate (not published yet) is looking for `master` and `main`.  
If you want to change the branch, you can use the `--branch` option, as you did it [there](https://github.com/godot-rust/godot-rust-template/pull/23/files) in `sh/test-template.sh`, line 17.

**Comment by macalimlim** [comment]
Hi, @k0pernicus uhhm I'm confused how it will work when someone pushed a PR from a fork of the template.

**Comment by k0pernicus** [comment]
When someone wants to push something he will have to make his remote & branch public, and I think you can have this information using a Travis environment variable to fork & test it.

**Comment by macalimlim** [comment]
closing this, will be using github actions instead
