### ISSUE TITLE
Codingame rust template

### ISSUE THREAD

**Issue by NangiDev** [cargo-generate/cargo-generate#260]
I created this template for codingame projects.
https://github.com/NangiDev/rust-codingame-template

The template sets up a project to be used with https://github.com/slava-sh/rust-bundler to generate a single file.
Then I use codingame's own chrome extension and app to automatically sync the singlefile.rs to the website.

It creates a pretty good workflow.

**Comment by NangiDev** [comment]
Seems to be some problems with the rust-bundler and newer version of rust.
It does not understand keyword crate

**Comment by NangiDev** [comment]
A fix has been requested from Mariomka to fix this issue. Waiting for review/accept or you can use Mariomka's version by building it manually

https://github.com/mariomka/rust-bundler

**Comment by k0pernicus** [comment]
Hi,  
do not hesitate to make a PR in order to introduce your project inside our TEMPLATE.md file 😉

**Comment by sassman** [comment]
Hi @NangiDev,

just wanted to check back if you still plan to create PR for the template suggestion or shall we close this issue?
