### ISSUE TITLE
Project state: it's time to fork

### ISSUE THREAD

**Issue by k0pernicus** [cargo-generate/cargo-generate#270]
After trying my best to maintain as good as possible this project, it is time for me to stop there.

I am facing several issues now:
1. the build / merge system is broken due to an error (as you may found [here](https://github.com/ashleygwilliams/cargo-generate/pull/264) for example) between Travis and the Github API - based on the solution described [here](https://github.community/t/expected-waiting-for-status-to-be-reported/16727), it seems I have to modify the settings of the project in order bypass an outdated setting... unfortunately, I don't have the right accesses to go into the project settings. I tried to contact several times the original creator / maintainer of cargo-generate to do something here but I did not received any news from her.
2. I don't use cargo-generate enough anymore to know "what is good for the project". To me, the best maintainer of a project is a person who uses it (almost) every day, and I think also that some project contributors (@sassman for example) would be better maintainers than me today. Unfortunately, as I don't have any access to the settings, I can't give this role to someone...
3. I had hard times to maintain my own projects last year, and I will have less time to maintain them this new year, so it's time for me to focus on something I want to use **and** maintain.
4. I am not the only maintainer of this project, but it became very difficult to obtain responses from other maintainers the last months unfortunately.

Those are the reasons I think it is time to fork this project now.

***Note for the comments***: **I don't blame anyone for the maintenance and you should not blame anyone too**. Open Source is great to develop and share new ideas, features, remarks... and share different "versions" (forks) of a given project.  
Also, we all had a shitty year...
It's time to move on, but not the time to blame anyone here 😉

If you want to maintain a fork of cargo-generate (**warning**: be aware before that maintaining an open-source project is a lot of responsabilities), please respond to this thread with the crate name & github URL of your fork.

If you are an existing maintainer of this project, have an access to the project settings to fix the current issue(s), and want to maintain back this project, feel free! 😃

All the best 👋

**Comment by sassman** [comment]
What a sad day for the project. But of course totally understandable. So all the best for your future projects.

I'd like to avoid the forking if possible, and would rather ask the maintainers or the owner @ashleygwilliams to support me on that matters to maybe hand over some capabilities (meaning access to the settings etc). 
The reason is IMO too many abandoned crates does not contribute well to the health of the rust ecosystem and that's why I prefer to invest into the future of a crate rather than let it rot.

If those things can be arranged I'd be more than happy to step up and keep this project alive.

**Comment by k0pernicus** [comment]
I totally agree: avoid to fork and continue to maintain the project is way better than a fork...  
Unfortunately, it seems my comments & mails did not reached the original maintainer.

Thanks in advance @sassman :)

**Comment by sassman** [comment]
@k0pernicus I reached out to @ashleygwilliams and she proposes a handover / kickoff call this weekend, you wanna participate or are completely out?

**Comment by sassman** [comment]
Anyone else interested?

@EverlastingBugstopper

**Comment by EverlastingBugstopper** [comment]
hey! i appreciate the ping but i'm not really working on any projects tangential to `cargo-generate` anymore and like @k0pernicus said it likely makes sense for folks a bit more invested in the project/open to maintenance responsibilities to take the reins on this.

**Comment by k0pernicus** [comment]
Awesome @sassman, thanks. I discussed a bit with @ashleygwilliams and I may be available this weekend.  
Do not hesitate to invite me, but if I don't answer I will certainly be busy with the family :)

**Comment by sassman** [comment]
I think we have successfully prevented the forking, thanks to @ashleygwilliams we got now an own gh org for cargo-generate, that allows us to operate more independently and make faster decisions. 
Also the ci/cd issues is currently WIP and hopefully soon fixed.

If that would be ok for you @k0pernicus we may can close this issue :)

**Comment by k0pernicus** [comment]
Thanks all for this awesome work :)

Long life to cargo-generate 🎉
