### ISSUE TITLE
type annotations needed

### ISSUE THREAD

**Issue by yanv1991** [cargo-generate/cargo-generate#279]
getting error in the installation Compiling cargo v0.46.1
error[E0283]: type annotations needed

```
seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                               ^^^^^^ cannot infer type for struct `std::string::String```

**Comment by sassman** [comment]
Can you please provide your cargo and rustc versions?

**Comment by Gago55** [comment]
> Can you please provide your cargo and rustc versions?

I've exact same problem when I'm trying to install cargo-generate. My cargo and rustc version is 1.49.0

**Comment by k0pernicus** [comment]
Hi,
Can you try to update your local version to master please?

I tried to build the latest version of cargo-generate (0.5.2) using cargo and rustc version 1.49.0 and did not had any issue at all...  
However, `cargo install cargo-generate` failed in my machine *but* the version on crates.io is not the latest one (cargo-generate v0.5.1, not 0.5.2).

OS: xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64 (macOS ARM)

**Comment by sassman** [comment]
We hope to release v0.5.2 very soon, in fact all is tagged and ready just not yet on crates.io due to organisational issues.

**Comment by lindeneau-scott** [comment]
I cannot install either v0.5.1 or v0.5.2 (master) with rustc/cargo 1.49.0 or 1.48.0.

![image](https://user-images.githubusercontent.com/51243227/105783491-72d92d00-5f2b-11eb-886f-0ba917c1e13a.png)

```
➜  lindeneau.scott cargo install cargo-generate
    Updating crates.io index
  Installing cargo-generate v0.5.1
   Compiling libc v0.2.82
   <--- SNIP --->
   Compiling cargo v0.46.1
error[E0283]: type annotations needed
   --> /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.46.1/src/cargo/util/config/de.rs:471:63
    |
471 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: failed to compile `cargo-generate v0.5.1`, intermediate artifacts can be found at `/tmp/cargo-installVfZ1hq`

Caused by:
  could not compile `cargo`

To learn more, run the command again with --verbose.
➜  lindeneau.scott rustc --version             
rustc 1.49.0 (e1884a8e3 2020-12-29)
➜  lindeneau.scott cargo --version             
cargo 1.49.0 (d00d64df9 2020-12-05)
```

```
lindeneau.scott cargo install --git https://github.com/cargo-generate/cargo-generate.git
    Updating git repository `https://github.com/cargo-generate/cargo-generate.git`
  Installing cargo-generate v0.5.2 (https://github.com/cargo-generate/cargo-generate.git#6dd88ed3)
    Updating crates.io index
   Compiling libc v0.2.82
   <--- SNIP --->
   Compiling git2-curl v0.14.1
error[E0283]: type annotations needed
   --> /home/scott/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.50.0/src/cargo/util/config/de.rs:530:63
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: failed to compile `cargo-generate v0.5.2 (https://github.com/cargo-generate/cargo-generate.git#6dd88ed3)`, intermediate artifacts can be found at `/tmp/cargo-installNBhTuj`

Caused by:
  could not compile `cargo`

To learn more, run the command again with --verbose.
➜  lindeneau.scott cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
➜  lindeneau.scott rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by lindeneau-scott** [comment]
Apparently this is an issue caused by a failure in an upstream component and should be patched in an upcoming release. 

Workaround:
```
cargo install cargo-generate --locked cargo
```

Temporary workaround from the same thread:
https://github.com/rust-lang/cargo/issues/9101

**Comment by sassman** [comment]
Seems that the latest serde version causes this problem, as you can also see in [pull/278](https://github.com/cargo-generate/cargo-generate/pull/278)

**Comment by Corfucinas** [comment]
Following this thread (same error as above).

**Comment by milespossing** [comment]
> Seems that the latest serde version causes this problem, as you can also see in [pull/278](https://github.com/cargo-generate/cargo-generate/pull/278)

Man this is the second issue I've seen with a breaking change in serde in as many months

**Comment by sassman** [comment]
The latest version of serde in [pull/287](https://github.com/cargo-generate/cargo-generate/pull/287) solves this issue. 

Release v0.5.3 is in preparation and will fix it.

**Comment by sassman** [comment]
[Release v0.5.3](https://github.com/cargo-generate/cargo-generate/releases/tag/v0.5.3) is now out, problem should be solved.

@yanv1991 could you please double check?

**Comment by Corfucinas** [comment]
@sassman 

I managed to install it without problems `cargo install cargo-generate` on Ubuntu 20.04
