### ISSUE TITLE
mdbook for every feature with some useful examples

### ISSUE THREAD

**Issue by sassman** [cargo-generate/cargo-generate#299]
As a developer
I want to read about every feature in a nice mdbook
So that I can get also nice examples of how to use features presented

Not all given and coming features are well documented in the `README.md` also Template variables are way to detailed documented for a `README.md`. 

My proposal is to start a mdbook with a little Quick Start chapter and then for every feature a little chapter that would also explain with some rich examples the potential of every feature.

**Comment by MarcoIeni** [comment]
I am one of the maintainers of https://github.com/rust-unofficial/patterns
We have a continuous deployment with github actions that updates https://rust-unofficial.github.io/patterns/ for every commit and a continuous integration that does some check on every commit.
If you want I can setup something similar for cargo-generate.
Create a `book` repository under this org, enable github pages in the settings and I will do a PR to setup a book that contains an "hello world".
![image](https://user-images.githubusercontent.com/11428655/109870273-2f7c8780-7c6a-11eb-8c6d-3a3046d2b6d4.png)

**Comment by sassman** [comment]
Thanks for the offer @MarcoIeni. Sounds pretty awesome. 
The only thing I'm still a bit hesitating, is if an own mdbook is justified or not, I'm not sure if we hit that complexity level already or not.

**Comment by MarcoIeni** [comment]
What's the alternative?

**Comment by sassman** [comment]
The alternative would be to keep things simple, and stick to the README.md in the repo and link examples to repositories (to demonstrate the configurabilities)

**Comment by MarcoIeni** [comment]
I think that an mdbook could be nice, but we can wait for the opinions of other users.

**Comment by joshrotenberg** [comment]
> I think that an mdbook could be nice, but we can wait for the opinions of other users.

I'm a 👍 on an mdbook for what its worth. READMEs are good, too, but I find mdbooks easier to read and navigate, especially as the options and complexity increase.

**Comment by sassman** [comment]
with #519 we have now an own book :)

Big Thanks to @joshrotenberg for this huge contribution.
