### ISSUE TITLE
Git Error: an unknown git error occurred; code=NotFound (-3)

### ISSUE THREAD

**Issue by jonas-schievink** [cargo-generate/cargo-generate#302]
I'm getting an unhelpful error in this CI run that I can't pinpoint to the actual problem: https://github.com/knurling-rs/app-template/pull/46/checks?check_run_id=1971245356

Any ideas as to what might be causing this? Locally it all seems to work fine, even with detached HEAD.

**Comment by sassman** [comment]
Hi there, I commented on the PR of yours.

TL;DR: [checkout our github workflow config](https://github.com/cargo-generate/cargo-generate/blob/master/.github/workflows/build.yml#L80), that was also causing issues.

**Comment by sassman** [comment]
@jonas-schievink I've added an [e2e test](https://github.com/cargo-generate/cargo-generate/actions/runs/625259929) to be able to verify this behaviour when using cargo-generate on ci runs. 

However, as you can see the runs where all successful, could it be that there is an issue in the template repo that you folks are using?

**Comment by PI-Victor** [comment]
cargo-generate is incompatible with overwriting git connection protocol

if you have this in your `~/.gitconfig`:

```
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```

comment it out.

**Comment by sassman** [comment]
will close this one, and promote #325 to the tracking issue.
