### ISSUE TITLE
Respect the default branch when generating from git

### ISSUE THREAD

**Issue by autodidaddict** [cargo-generate/cargo-generate#304]
This comes up a lot when the template in git has a default branch of `main` rather than `master`. Cargo generate assumes that the default branch name is `master`, and so people get strange errors when trying to generate from a repository that doesn't use `master` as the default.

**Comment by sassman** [comment]
What version do you use?

Should be closed since #263 got merged and version v0.5.3 shipped it.

**Comment by autodidaddict** [comment]
I was on 0.3.0, my apologies. I _always_ forget to do a `force` when installing.

Honestly I think `cargo update` should update all of the things you've `cargo install`ed as well. this would avoid a lot of unnecessary confusion like this.

**Comment by sassman** [comment]
no worries.

This might be then for you:

```sh
cargo install cargo-update
cargo install-update -a
```

it will take care of updating all `cargo install`ed binaries in one shot.

**Comment by autodidaddict** [comment]
Oh nice. I did not know about that crate.
