### ISSUE TITLE
Got `SSL error` if using behind a proxy

### ISSUE THREAD

**Issue by metalwhale** [cargo-generate/cargo-generate#327]
### The Bug
I'm getting this error while trying to use `cargo generate` behind a proxy server:
```
Error:  Git Error: SSL error: syscall failure: Connection reset by peer; class=Os (2)
```
The cause seems to be related to the proxy settings on my machine, but since I have already set `HTTP_PROXY` and `HTTPS_PROXY` and the `git clone` command didn't give any error so I think this bug may be not about `git` itself but `cargo-generate`.

### Assumption
I think this bug is caused by the fact that `git::create` does not make connection using the proxy options even if there are proxy environment variables in the `git` configuration.

### Proposal
Force the `create` method in [`git.rs`](https://github.com/cargo-generate/cargo-generate/blob/master/src/git.rs) to use the proxy settings by default.
Change this:
```rust
pub(crate) fn create(project_dir: &Path, args: GitConfig) -> Result<String> {
    //
            git_remote.connect(git2::Direction::Fetch)?;
    //
}
```
To this:
```rust
pub(crate) fn create(project_dir: &Path, args: GitConfig) -> Result<String> {
    //
            let mut proxy = ProxyOptions::new();
            proxy.auto();
            git_remote.connect_auth(git2::Direction::Fetch, None, Some(proxy))?;
    //
}
```

### Environment information
- `cargo --version`:
```
cargo 1.51.0 (43b129a20 2021-03-16)
```
- `rustc --version`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by sassman** [comment]
Thanks for the detailed bug report.
I think writing a test first will bring clarity if the assumptions uphold.

However, if so, then we need to figure out if there are cases where the auto detect for proxy settings can cause harm and screw up git URL's where no proxy setting is there.

**Comment by joshrotenberg** [comment]
> /to @joshrotenberg @metalwhale
> since quite some commands like curl and git behave the way to check for the env vars `HTTP{S}_PROXY` and if present just use them, it is quite reasonable to assume that this is common sense. Hence I'm going to take the first proposed approach and come up with a PR soon.

If its not a duplication of work you've already started, I'd like to give this a go.
