### ISSUE TITLE
could not compile cargo-generate

### ISSUE THREAD

**Issue by aikcn** [cargo-generate/cargo-generate#341]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.24tbpm6nt480co8m.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.2l44pf2s4ffriyu6.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.2lt3469i7mk2j79.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.3b5pehg7eiv4s35.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.3ceh30vba033srcj.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.3edz4c4a60xtyfuw.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.3fi5589rim7t8kqn.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.48ng1c1m940s1f6j.rcgu.o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.x65gsw9xhcixxrw.rcgu.o" "-o" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate" "/Downloads/cargo-generate-0.6.1/target/debug/deps/cargo_generate.m5edenmwr3vwwa1.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Downloads/cargo-generate-0.6.1/target/debug/deps" "-L" "/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib/darwin" "-L" "/Downloads/cargo-generate-0.6.1/target/debug/build/curl-sys-bd2f23773b5b1731/out/build" "-L" "/Downloads/cargo-generate-0.6.1/target/debug/build/libnghttp2-sys-af9437c24649f0c5/out/i/lib" "-L" "/Downloads/cargo-generate-0.6.1/target/debug/build/libgit2-sys-e64869ced3eabf0a/out/build" "-L" "/Downloads/cargo-generate-0.6.1/target/debug/build/libssh2-sys-d489b3bca2c0ece6/out/build" "-L" "/opt/local/lib" "-L" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcargo_generate-1e9fe96555329b38.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libstructopt-a910e4bc3fe587a3.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libheck-77ad3a50770dacfb.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libliquid-548048031d0a77fc.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libliquid_lib-4843ff7be7af290e.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libunicode_segmentation-06a2cd4836482825.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libdoc_comment-af41553722bce974.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libthiserror-c47c9f950bbcca81.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libindicatif-15ed3bd575014557.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libnumber_prefix-eee5a285cacaca6d.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libliquid_core-b33cf15369423d62.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libanymap-f3187c06eb1619c8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libitertools-93bb6b43cf6e9964.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libeither-85c9ed1465ab84fa.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libpest-5fee79bb83c24d24.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libucd_trie-da308f76654fea06.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libchrono-3e05425f33eb2df8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libnum_integer-57d3f0d810d9d207.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libnum_traits-1ce56ba14ce8cf1b.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtime-922e8430f1e36711.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libkstring-02dc1f0d3ec4af92.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libdialoguer-0e419b9a272695ab.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libzeroize-74e51f3884d8ec92.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libremove_dir_all-3a5586255ab405f5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcargo-59c8edcbfb2a6395.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libhex-0ddadfb3ef7e75e7.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libhome-82175aab280b11fd.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libopener-1e71448dcc1e065c.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libunicode_xid-2e796002d9eaa3a5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libim_rc-05e25591af1db3a1.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librand_xoshiro-fc496727e6cdc50e.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librand_core-aeb762c0fb097861.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libsized_chunks-1eb54d542e04b230.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libbitmaps-0176acafd46676ad.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtypenum-5108beaff1d07dd1.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtoml-407ea4296c6b739f.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libstrip_ansi_escapes-21cb648f2a1957c5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libvte-94e380847724d192.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libutf8parse-f0e608fde5ccb7e0.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libhumantime-5b76cf3753c23c01.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libnum_cpus-58037065f2a51473.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libserde_ignored-a2aa2bf493deb150.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcrypto_hash-de7f6cf3cc48fff4.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libhex-0e3ad0283dcb6dbe.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcommoncrypto-f8ad4e82ff009568.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcommoncrypto_sys-2cd6d884bb2dff2d.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libshell_escape-3d3d67e4d03c82fd.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcore_foundation-7f7c9c6f84565586.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcore_foundation_sys-f116c06fe325cc56.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libclap-916cf643f0670087.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libvec_map-324341f00650df72.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtextwrap-6b3555f21353bb15.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libstrsim-1b55d843406b69e9.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libatty-4060068d13a3c6f4.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libansi_term-3a2dfb7aa76ed710.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libignore-8243cb58d4606e50.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libwalkdir-73dbd92226a8c009.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libthread_local-119adae422674cca.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libonce_cell-ec75d9fad6e2a440.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libsame_file-3e9470389f4adfb2.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libglobset-3d67c2ce332a07a8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libfnv-9095fa26297347d6.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libbstr-63fc6d860c688ee4.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libregex_automata-0eb5eb733796fe28.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libbyteorder-59a279b895e5613a.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcrates_io-f7c9d3fdafc0f50c.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librustfix-2058f052cd2aada8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libserde_json-a2331462c1e1cf00.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libryu-5cc3bf14a150c735.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libitoa-36f52192716eb05f.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtar-e406b7917ec89f3a.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libflate2-9c1e19b64b2f57c2.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcrc32fast-be373239aa3d20a4.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtempfile-1afd421fe51d5906.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librand-c2ab595fd4b3155c.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librand_chacha-82bb2a009f30b75e.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libppv_lite86-c912a9779d19921b.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/librand_core-71aa6a1ce6882d57.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libgetrandom-954c360d847634b4.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libremove_dir_all-77431bbd4850e953.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libglob-f252ec5c39bd9cd5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtermcolor-f52607f467ddcaaa.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcurl-eabcebeda3d2a3cd.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libsocket2-e4e72166f7057cde.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcurl_sys-af75e4d42e6ff472.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblibnghttp2_sys-566924bd69c279a8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libbytesize-2e2649e0330830e0.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcrossbeam_utils-7a9719ec651ac1d1.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblazycell-1480b2b812e8ef34.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libjobserver-9d1ba6aa30977d03.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libfiletime-48f14fb70d338140.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libsemver-160059c06a36b1e5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libsemver_parser-005e2db99ee70313.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcargo_platform-84b4bec8208b5953.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libconsole-f8b656e7d564e648.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libterminal_size-a3c80757862fc640.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libregex-aa0d3cf79df3bc65.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libregex_syntax-bc8f537d65115d9b.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libaho_corasick-88471f203699b608.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libmemchr-5116593d8ce84761.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libunicode_width-8e8dc5d4e8fc98cd.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblazy_static-391df1873a90d3f6.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libgit2-b950e2e40972b4fd.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liburl-6a709a2b98633315.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libidna-8891fe8ff21c0e98.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libunicode_normalization-7ef91a432c606eee.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtinyvec-e8b24f503f0ed028.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libtinyvec_macros-0f243429f4ed5cc2.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libunicode_bidi-5e2aed0d96a27248.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libform_urlencoded-8f3d13350149ae06.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libpercent_encoding-037bf7756eb83570.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libmatches-8f92a6e55e3e3200.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblog-5e46e81b156f37b5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libcfg_if-a39bd604bcf576ca.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblibgit2_sys-16ace4e46488fc71.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblibssh2_sys-dd8b2d65cb7a43c7.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libopenssl_sys-9905f5de428b64e8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblibz_sys-1f06d6f0f9bd1dc8.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/liblibc-fa548d035587df27.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libbitflags-cc063fb1f3807ae0.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libserde-4a7f0779a608f1c5.rlib" "/Downloads/cargo-generate-0.6.1/target/debug/deps/libanyhow-cbae2012dea9e134.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-03b7cc8bb9584efc.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-43536cfc9c9c300b.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-bfb93f6c6a903396.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-d52ee6765e48d9ae.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-b56132c9450bbaec.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-ed4cd0fbab7349ac.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-7a404b4047191342.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-f401a975d7880a1f.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-d9dee5a9f052ffe0.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-c73f1ebf99827aaf.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-b612ef1ed5c9489f.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-0498d3220acc297c.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-da050587f0859a64.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-bc5bda1ff8b653f1.rlib" "/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f86ac61d31791301.rlib" "-framework" "CoreFoundation" "-lclang_rt.osx" "-framework" "Security" "-framework" "CoreFoundation" "-liconv" "-framework" "Security" "-framework" "CoreFoundation" "-lssl" "-lcrypto" "-lz" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv"
  = note: Undefined symbols for architecture x86_64:
            "_iconv", referenced from:
                _git_path_iconv in liblibgit2_sys-16ace4e46488fc71.rlib(path.o)
               (maybe you meant: _git_path_iconv, _git_path_iconv_clear , _git_path_iconv_init_precompose )
            "_iconv_close", referenced from:
                _git_path_iconv_clear in liblibgit2_sys-16ace4e46488fc71.rlib(path.o)
            "_iconv_open", referenced from:
                _git_path_iconv_init_precompose in liblibgit2_sys-16ace4e46488fc71.rlib(path.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error

error: could not compile `cargo-generate`

To learn more, run the command again with --verbose.

**Comment by sassman** [comment]
Could you please check if you have a gcc installed?

**Comment by aikcn** [comment]
> Could you please check if you have a gcc installed?
TKS!

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by sassman** [comment]
I found a very similar (maybe the same root cause) issue [here](https://github.com/rust-lang/git2-rs/issues/180).

Maybe it is worth to try out with vendored ssl too. `cargo install cargo-generate --features vendored-openssl` 
Can you also provide the macOS version you're running?

**Comment by aikcn** [comment]
> I found a very similar (maybe the same root cause) issue [here](https://github.com/rust-lang/git2-rs/issues/180).
> 
> Maybe it is worth to try out with vendored ssl too. `cargo install cargo-generate --features vendored-openssl`
> Can you also provide the macOS version you're running?

Thank you too much!
I found a solution: https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx

**Comment by sassman** [comment]
Was this the Final command That fixed it for you?

`sudo port deactivate libiconv`

**Comment by aikcn** [comment]
> Was this the Final command That fixed it for you?
> 
> `sudo port deactivate libiconv`

yes

**Comment by nurse-the-code** [comment]
Yeah, this worked for me too:

Disable libiconv from MacPorts:
```zsh
sudo port deactivate libiconv
```
Then the installation succeeded.

You may need to reactivate libiconv if some of your Macports applications are not working:
```zsh
sudo port activate libiconv
```
