### ISSUE TITLE
error: failed to run custom build command for `curl-sys v0.4.43+curl-7.76.0` on cygwin (Windows 10)

### ISSUE THREAD

**Issue by jhunnius** [cargo-generate/cargo-generate#350]
I'm not an expert in how the dependency system works, so I'm not sure whether the issue is in cargo-generate or cargo (the last dependency that the build tried to compile). Maybe it could help to specify an explicit version of curl-sys and curl, or cargo.

Update: Building cargo-0.53.0 itself (git clone https://github.com/rust-lang/cargo && cd cargo && cargo build --release) throws the same error, I'll post the bug report there.

Log:

   Updating crates.io index
   Installing cargo-generate v0.6.1
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
...
...
   Compiling cargo v0.52.0
The following warnings were emitted during compilation:

warning: gcc: fatal error: no input files
warning: compilation terminated.
warning: gcc: fatal error: no input files
warning: compilation terminated.

error: failed to run custom build command for `curl-sys v0.4.43+curl-7.76.0`

Caused by:
  process didn't exit successfully: `C:\cygwin64\tmp\cargo-installbJGSYg\release\build\curl-sys-9fd8b6919fe5eefd\build-script-build` (exit code: 1)
  --- stdout
  cargo:root=C:\cygwin64\tmp\cargo-installbJGSYg\release\build\curl-sys-0854f4c58ee1a36a\out
  cargo:include=C:\cygwin64\tmp\cargo-installbJGSYg\release\build\curl-sys-0854f4c58ee1a36a\out\include
  cargo:static=1
  cargo:rustc-cfg=link_libnghttp2
  cargo:rustc-cfg=link_libz
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\li
bnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\libz-sys-968ff0acde6cac4d\\out/include" "-DBUILDING_LIBCURL" "-D
CURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISAB
LE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "
-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_STATICLIB" "-DU
SE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\c
url-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/asyn-thread.o" "-c" "curl/lib/asyn-thread.c"
  cargo:warning=gcc: fatal error: no input files
  cargo:warning=compilation terminated.
  exit code: 1
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\li
bnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\libz-sys-968ff0acde6cac4d\\out/include" "-DBUILDING_LIBCURL" "-D
CURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM" "-DCURL_DISAB
LE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DHAVE_ASSERT_H" "
-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_STATICLIB" "-DU
SE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\c
url-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/altsvc.o" "-c" "curl/lib/altsvc.c"
  cargo:warning=gcc: fatal error: no input files
  cargo:warning=compilation terminated.
  exit code: 1

  --- stderr
  fatal: not a git repository (or any parent up to mount point /cygdrive)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "curl/lib" "-I" "curl/include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\rel
ease\\build\\libnghttp2-sys-0421b25a89b26c34\\out\\i\\include" "-I" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\release\\build\\libz-sys-968ff0acde6cac4d\\out/include" "-DBUILDI
NG_LIBCURL" "-DCURL_DISABLE_CRYPTO_AUTH" "-DCURL_DISABLE_DICT" "-DCURL_DISABLE_GOPHER" "-DCURL_DISABLE_IMAP" "-DCURL_DISABLE_LDAP" "-DCURL_DISABLE_LDAPS" "-DCURL_DISABLE_NTLM
" "-DCURL_DISABLE_POP3" "-DCURL_DISABLE_RTSP" "-DCURL_DISABLE_SMB" "-DCURL_DISABLE_SMTP" "-DCURL_DISABLE_TELNET" "-DCURL_DISABLE_TFTP" "-DCURL_STATICLIB" "-DENABLE_IPV6" "-DH
AVE_ASSERT_H" "-DOS=\"unknown\"" "-DHAVE_ZLIB_H" "-DHAVE_LIBZ" "-DHAVE_GETADDRINFO" "-DHAVE_GETPEERNAME" "-DHAVE_GETSOCKNAME" "-DCURL_DISABLE_FTP" "-DUSE_NGHTTP2" "-DNGHTTP2_
STATICLIB" "-DUSE_WINDOWS_SSPI" "-DUSE_SCHANNEL" "-DWIN32" "-DUSE_THREADS_WIN32" "-DHAVE_IOCTLSOCKET_FIONBIO" "-DUSE_WINSOCK" "-o" "C:\\cygwin64\\tmp\\cargo-installbJGSYg\\re
lease\\build\\curl-sys-0854f4c58ee1a36a\\out\\build\\curl/lib/asyn-thread.o" "-c" "curl/lib/asyn-thread.c" with args "gcc.exe" did not execute successfully (status code exit
code: 1).

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.6.1`, intermediate artifacts can be found at `C:\cygwin64\tmp\cargo-installbJGSYg`

Caused by:
  build failed

**Comment by k0pernicus** [comment]
Hi @jhunnius,
It seems related to this issue: https://github.com/rust-lang/cargo/issues/9509, which has been closed / fixed recently.

Will close this one then :)
