### ISSUE TITLE
Get SIGSEGV when I try to install

### ISSUE THREAD

**Issue by violetastcs** [cargo-generate/cargo-generate#360]
Hello, when I try to install this via `cargo install cargo-generate`, eventually I get the error:
```
   Compiling cargo-platform v0.1.1
   Compiling liquid-core v0.22.0
   Compiling rustfix v0.5.1
   Compiling liquid-lib v0.22.0
   Compiling liquid v0.22.0
   Compiling crates-io v0.33.0
error: failed to run custom build command for `cargo v0.52.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install5nDBAt/release/build/cargo-401a90988d28e8ee/build-script-build` (signal:
11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.6.1`, intermediate artifacts can be found at `/tmp/cargo-install5nDBAt`

Caused by:
  build failed
```

I am on Alpine Linux. `uname -a`:
```
Linux archlabs 5.10.44-0-lts #1-Alpine SMP Fri, 18 Jun 2021 06:01:53 +0000 x86_64 GNU/Linux
```
(Ignore the "archlabs" part, that's just my hostname)

**Comment by sassman** [comment]
@violetastcs that is very interesting. 
For curiosity could you may try out `cargo install --locked cargo-generate` and see if that appears there too?

**Comment by sassman** [comment]
@violetastcs is this problem still present?

**Comment by taurr** [comment]
I just installed `cargo-generate` into a `Alpine` docker image - had to install
 * `curl`
 * `rust`
 * `llvm`
 * `clang`+`gcc` (as `clang` alone didn't provide me with `cc`)
 * `musl-dev`
 * `openssl` + `openssl-dev`
but then `cargo install cargo-generate` worked without problems.

**Comment by taurr** [comment]
Just to be safe - I just installed a new VM with newest `Alpine` iso image.

Installed `cargo-generate` without problems, ran just fine.

**Comment by taurr** [comment]
@sassman: I think this can be closed
