### ISSUE TITLE
Prebuild Binaries Again

### ISSUE THREAD

**Issue by jashandeep-sohi** [cargo-generate/cargo-generate#378]
`cargo-generate` is useful enough outside of the Rust ecosystem for templating projects that it's worth while to have pre-built binaries available for non-Rustaceans. Also nice to have a single source of truth to pull binaries from for any CI jobs.

Looks like `v0.5.1` was the last release with binary assets attached. PR #377 does something similar via GH Actions.

**Comment by sassman** [comment]
lgtm. 

Thanks for your contribution, very appreciated.

**Comment by sassman** [comment]
@jashandeep-sohi do you know if there is a delay between the GH Release creation and the GH Actions workflow being triggered? 

I'm asking because the GH Release for `v0.7.2` should have triggered the workflow already, but this did not happened to now (15min past the trigger). Maybe that is expected behaviour thou.

**Comment by jashandeep-sohi** [comment]
Huh...interesting. When I was testing manually it was immediate. Let me look into it.

**Comment by jashandeep-sohi** [comment]
@sassman Ahhh turns out if you make API requests using the auto generated Actions `GITHUB_TOKEN` it doesn't generate any events apparently to prevent "accidentally creating recursive workflow runs". :roll_eyes: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by sassman** [comment]
You have created and published the GH Release manually right? It might be that this is the key to get it working. 

[As you can see](https://github.com/cargo-generate/cargo-generate/actions/runs/1054413575/workflow) the workflow takes care of creating the GH Release, so that might then not trigger follow-ups.

**Comment by jashandeep-sohi** [comment]
I can either rework this so that it's part of the main release workflow or you can create a personal access token for the job?

**Comment by sassman** [comment]
What might help, is to change the `on` trigger to something like shown here:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/329682/126576350-7aaca228-216b-4200-b99e-572b4b36d9f5.png">

So the event would not be the GH Release creation, but the successful completion of the "Release" workflow run

**Comment by jashandeep-sohi** [comment]
True, that might work too.

**Comment by sassman** [comment]
> I can either rework this so that it's part of the main release workflow
I'd rather not do this, in favour of smaller separated pipelines.

> or you can create a personal access token for the job
I will also have a look at this then.

**Comment by jashandeep-sohi** [comment]
Actually maybe no. The release event has info about the git sha & branch name. I don't know if a workflow completed event would have it too.

**Comment by jashandeep-sohi** [comment]
> > I can either rework this so that it's part of the main release workflow
> 
> I'd rather not do this, in favour of smaller separated pipelines.
> 
> > or you can create a personal access token for the job
> 
> I will also have a look at this then.

Agreed, but PATs have their own security problems. i.e. you can't scope them to a particular repo and they're associated with a github account (not the repo or org)

**Comment by sassman** [comment]
I've prepared a GH PAT and made small adjustments on the pipelines. Let's see how this works out.

For v0.7.2 I've worked around the problem by deleting and recreating the GH Release, and all artefacts had been created as expected.

Thanks for your work and help!
