### ISSUE TITLE
RFC: How to have CI for templates?

### ISSUE THREAD

**Issue by fitzgen** [cargo-generate/cargo-generate#40]
The https://github.com/rustwasm/rust_wasm_template template has travis ci pre-configured. We use travis to make sure that the template doesn't break. But it *also* works out so that if you clone the template, all you have to do is flip the switch in your travis ci dashboard to also get ci set up and configured.

In the process of moving that template over to `cargo-generate`, the template's CI is broken because of all the `{{variables}}`. I could fix this by making the CI script run `cargo-generate` and test the generated template, but now I have two different CI scripts: one for the template and another for the projects generated from the template.

How can we maintain a single CI script for both?

---------------------------------

<details><summary>The Output of Broken Builds Before cargo-generate Fills in Variables</summary>

```
$ cargo +nightly build --release --target wasm32-unknown-unknown
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling unicode-xid v0.1.0
   Compiling serde v1.0.59
   Compiling wasm-bindgen-shared v0.2.12
   Compiling dtoa v0.4.2
   Compiling cfg-if v0.1.3
   Compiling itoa v0.4.1
   Compiling log v0.4.3
   Compiling proc-macro2 v0.4.8
   Compiling quote v0.6.2
   Compiling syn v0.14.0
   Compiling serde_json v1.0.17
   Compiling serde_derive v1.0.59
   Compiling wasm-bindgen-backend v0.2.12
   Compiling wasm-bindgen-macro v0.2.12
   Compiling wasm-bindgen v0.2.12
   Compiling {{project-name}} v0.1.0 (file:///home/fitzgen/rust_wasm_template)
error: invalid character `{` in crate name: `{{project_name}}`

error: invalid character `}` in crate name: `{{project_name}}`

error: aborting due to 2 previous errors

error: Could not compile `{{project-name}}`.

To learn more, run the command again with --verbose.
```

</details>

**Comment by fitzgen** [comment]
Workaround: detect when teh template variables aren't filled out and tehn run `cargo-generate` on the template: https://github.com/rustwasm/rust_wasm_template/pull/16/commits/0318e23f516ce0346ee6c35938548a60f5ca5907

Is this the best solution for the problem?

**Comment by ashleygwilliams** [comment]
i have also been thinking about how to make this work. my originally guess was running cargo-generate on the template in CI- though i'm not 100% certain that's the best strategy? (it is realistic to how it will be used tho, so perhaps it is.) we should have something for 0.2.0 for this- i think it's crucial.

**Comment by killercup** [comment]
I believe this also depends very much on our decision on whether to require all files that should use substitutions to have a custom file name extension.

**Comment by ashleygwilliams** [comment]
@killercup do you wanna open an issue for discussion around that? would love to hear folks thoughts--

**Comment by killercup** [comment]
@ashleygwilliams here you go: #43

**Comment by fitzgen** [comment]
Maybe if `cargo generate` only considered a certain subdir the template (by configuration (with default) or convention or...), then the root of the repo could be used for CI etc.

**Comment by MarcoIeni** [comment]
So the problem is that you want to specify variables that not related to cargo generate in the format `{{variable-name}}`?
You can do it by:
- excluding the file via [include/exclude](https://github.com/ashleygwilliams/cargo-generate#include--exclude)
- use the format `{{ "${{ variable-name " }}}}`. See [example](https://github.com/rust-github/template/blob/2925bb978c8fd8b4ef184891d0a0c31ba077081b/.github/workflows/cd.yml#L11).
- use `{% raw  %}` and `{% endraw  %}`. See [example](https://github.com/rust-github/template/blob/2925bb978c8fd8b4ef184891d0a0c31ba077081b/.github/workflows/ci.yml#L6-L86) and [docs](https://shopify.github.io/liquid/tags/raw/).
