### ISSUE TITLE
TEMPLATES.md: add number of stars of each template

### ISSUE THREAD

**Issue by MarcoIeni** [cargo-generate/cargo-generate#401]
What do you think about putting a badge like ![GitHub Repo stars](https://img.shields.io/github/stars/rust-github/template?style=social) next to each template in the [TEMPLATES](https://github.com/cargo-generate/cargo-generate/blob/master/TEMPLATES.md) file?
```
![GitHub Repo stars](https://img.shields.io/github/stars/rust-github/template?style=social)
```
In this way the reader can have additional info about the templates without opening all of them.

**Comment by sassman** [comment]
A nice idea. 

But it might be that we want to favor the suggestion of in #405 to lower the entry barrier to provide templates.
Then the question is if this improvement still is worth the effort.

**Comment by taurr** [comment]
I'd say #405 makes this issue irrelevant.

No we can just [locate templates on github](https://github.com/topics/cargo-generate).

**Comment by MarcoIeni** [comment]
Agree!
