### ISSUE TITLE
Define outcome & test with invalid/undefined template values

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#402]
What happens if we define e.g. a choice parameter in `cargo-generate.tom`, but then assigns an invalid choice in the `template_values_file` or via the `--define` flags?

What about boolean, integer?

This issue came up as part of #392

**Comment by taurr** [comment]
What will/should happen if we use a variable that is not defined in `cargo-generate.toml`?

What if it is assigned via e.g. `--define`?

Is `cargo-generate.toml` only there to allow us to know the types of values we can query interactively?

**Comment by sassman** [comment]
My takes here are

- undefined variables can be provided without harm, they will simply not be used in the template and all is good
- if the type does not match an expected type (e.g. boolean is expected but a string is given) then we could do:
    - try parse the given value as the type we expect
    - print a warning if parsing failed and assign a default (e.g. `Default::default()`)
    - print an info that we have parsed the provided type as a different type (e.g. string was parsed as a boolean)
- if a choice parameter is expected and a given value does not fit the list we could print a warning but go ahead
