### ISSUE TITLE
cargo-generate doesn't work with repos in 'detached HEAD' status

### ISSUE THREAD

**Issue by riverar** [cargo-generate/cargo-generate#406]
Repro:
1. Create `dummy` directory
2. `git init`
3. Add a `dummy` file
4. `git add dummy`
5. `git commit -m "Initial commit"`
6. Edit `dummy`
7. `git add -u`
8. `git commit -m "Commit 2"`
9. `git checkout HEAD^`
10. `cargo generate --name dummy --git .\`

```
cargo generate --name dummy --git .\
Creating project called `dummy`...
Error:  Git Error: A repo has no Head
```

This is a common state to be in during PR CI scenarios.

Treating a checked out template as a folder, as opposed to a repo, would help a lot (https://github.com/cargo-generate/cargo-generate/issues/387) but not sure we'll fall into this check https://github.com/cargo-generate/cargo-generate/commit/d2211d28e8ad4d51856323e9ba7e7879dabae163. Ideally, a --directory or --folder parameter would be added instead of this fall-through behavior.

See also:
https://github.com/actions/checkout/issues/6

**Comment by taurr** [comment]
I agree on this - also useful when developing the templates as `cargo-generate` wouldn't try to do a `git clone` of the template, which leads to the issues you describe.

I would suggest to use `--path` though. Solely based on preference, and becase e.g. `cargo install` uses `--path` for this type of specification. Oh... and looking at `git --help` or basically any other CLI tool... `path` seems to be the word here 😃

**Comment by sassman** [comment]
The "path" to go 😁
