### ISSUE TITLE
Make `--identity` configurable in cargo-generate.toml and verbose error message

### ISSUE THREAD

**Issue by orhun** [cargo-generate/cargo-generate#418]
While using `cargo-generate` as follows, it assumes that SSH private key is in `$HOME/.ssh/id_rsa` which is not always the case. Also the error message is not helpful enough:

```sh
$ cargo generate --git git@github.com:rustwasm/wasm-pack-template.git --name mywasm
🔧   Creating project called `mywasm`...
Error: ⛔   Git Error: private key path was incorrect
```

I propose making the `--identity` argument mandatory for git-ssh checkouts, removing the `$HOME/.ssh/id_rsa` fallback and aborting with an error message if `--identity` is not provided. e.g.:

```sh
$ cargo generate --git git@github.com:rustwasm/wasm-pack-template.git --name mywasm
⚠️   Unable to load config file: /home/orhun/.cargo/cargo-generate.toml
Error: ⛔   Git Error: please provide your SSH identity

$ cargo generate --git git@github.com:rustwasm/wasm-pack-template.git --name mywasm --identity ~/.ssh/git
⚠️   Unable to load config file: /home/orhun/.cargo/cargo-generate.toml
💡   Using private key: `$HOME/.ssh/git` for git-ssh checkout
🔧   Creating project called `/home/orhun/gh/cargo-generate/mywasm`...
[ 1/12]   Done: .appveyor.yml
[ 2/12]   Done: .gitignore
[ 3/12]   Done: .travis.yml
[ 4/12]   Done: Cargo.toml
[ 5/12]   Done: LICENSE_APACHE
[ 6/12]   Done: LICENSE_MIT
[ 7/12]   Done: README.md
[ 8/12]   Done: src/lib.rs
[ 9/12]   Done: src/utils.rs
[10/12]   Done: src
[11/12]   Done: tests/web.rs
[12/12]   Done: tests
✨   Done! New project created /home/orhun/gh/cargo-generate/mywasm
``` 

I'd like to submit a PR.

**Comment by sassman** [comment]
I agree the error message is misleading and should be more specific.

I do not like to make `--identity` mandatory, because for me for example the default assumption would same me tons of typing time.

I'd rather suggest an overwriting of the default ssh identity file in the cargo-generate.toml config file in order to allow customizable identities.

**Comment by orhun** [comment]
> I do not like to make `--identity` mandatory, because for me for example the default assumption would same me tons of typing time.

Then the error message should at least say something like `Git Error: private key path was incorrect: /home/user/.ssh/id_rsa`

> I'd rather suggest an overwriting of the default ssh identity file in the cargo-generate.toml config file in order to allow customizable identities.

That's also applicable I think. There might be an entry such as `ssh_key` which will have the default value of `~/.ssh/id_rsa` so that the user will know what's the default.

**Comment by orhun** [comment]
Hello! I can work on this in the following days if this issue is still valid. Just let me know!

**Comment by wotori** [comment]
I'dont quite understand why i have this error even trying to access open repo
```Git Error: private key path was incorrect```

**Comment by wotori** [comment]
> > I do not like to make `--identity` mandatory, because for me for example the default assumption would same me tons of typing time.
> 
> Then the error message should at least say something like `Git Error: private key path was incorrect: /home/user/.ssh/id_rsa`
> 
> > I'd rather suggest an overwriting of the default ssh identity file in the cargo-generate.toml config file in order to allow customizable identities.
> 
> That's also applicable I think. There might be an entry such as `ssh_key` which will have the default value of `~/.ssh/id_rsa` so that the user will know what's the default.

Yeah, this would be much more clear for people like me dealing with Rust environment for the first time.
Thanks!

**Comment by sassman** [comment]
> This documentation save me tons of time. But I still don't get It, I can git pull without ssh, why do I need ssh for cargo generate

Well it's up to you, if you provide a `https` url to a GitHub repository cargo-generate will stick to `https` then, if you provide the ssh url then cargo-generate will use the default ssh key or the provided `--identity`

**Comment by wotori** [comment]
> > This documentation save me tons of time. But I still don't get It, I can git pull without ssh, why do I need ssh for cargo generate
> 
> Well it's up to you, if you provide a `https` url to a GitHub repository cargo-generate will stick to `https` then, if you provide the ssh url then cargo-generate will use the default ssh key or the provided `--identity`

ahhh, I see now. Thanks a lot!

**Comment by ForsakenHarmony** [comment]
Just ran into this (and `Error: ⛔   Git Error: authentication required but no callback set; class=Ssh (23); code=Auth (-16)` with an https url, probably because I have my git config set up to rewrite https git urls to ssh urls)

Does `cargo-generate` (/ `git2`(?)) not use ssh the same way git does?

I have my ssh key in the ssh agent, it doesn't exist anywhere in the file system, can it not use the key from there?

**Comment by sassman** [comment]
> Just ran into this (and Error: ⛔ Git Error: authentication required but no callback set; class=Ssh (23); code=Auth (-16) with an https URL, probably because I have my git config set up to rewrite https git URLs to ssh URLs)

I can confirm that it is related to the git rewriting.

I added this to my `~/.gitconfig`
```
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```

And that caused the same error:

```sh
❯ cargo generate cli --name bak2
💡   Using application config: /Users/d34dl0ck/.cargo/cargo-generate
Error: ⛔   Git Error: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
```

I created the separate issue #520 for it.

> I have my ssh key in the ssh agent, it doesn't exist anywhere in the file system, can it not use the key from there?

Unfortunately not yet. There is a tracking issue for the ssh-agent based authentication at #384
