### ISSUE TITLE
`cargo_generate_version` is not respected

### ISSUE THREAD

**Issue by MarcoIeni** [cargo-generate/cargo-generate#427]
I noticed that `cargo_generate_version` doesn't work. Docs [here](https://github.com/cargo-generate/cargo-generate#require-cargo-generate-version-from-template). 

I created a [branch](https://github.com/rust-github/template/blob/wrong-version-test/cargo-generate.toml) were I specified ther requirement:

```toml
[template]
cargo_generate_version = ">0.99.0"
```

But cargo generate still works if I run:

```
cargo generate --git https://github.com/rust-github/template --branch  wrong-version-test
```

Am I missing something?

**Comment by sassman** [comment]
Did you use the master branch version for testing?

**Comment by MarcoIeni** [comment]
Oooops, from master it works, sorry! 

With the following commands it works:
```
$ git clone https://github.com/cargo-generate/cargo-generate
$ cd cargo-generate
$ cargo run -- generate --git https://github.com/rust-github/template --branch  wrong-version-test
```
