### ISSUE TITLE
crate comment in `lib.rs` is wrong and misleading

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#447]
The tool has evolved a lot since the comment was written, and is both misleading and wrong.

As the comment doesn't contribute any testable examples nor any information that can't be found in a better version in `README.md`, I suggest we remove the comment entirely.

**Comment by sassman** [comment]
maybe you could pin point to what exactly you mean? I'm not getting the misleading thing you are referring to.

**Comment by taurr** [comment]
In general, the comment does not add information/value that is not already part of `README.md`.

It mentions stuff like what templates are and what they can do. How placeholders are specified in the config files etc. All of it is information that is part of `README.md`, and thus it **needs to be maintained both places**, and currently they are not in agreement.

For instance, the comment says:
> Right now, only git repositories can be used as templates.

Simply not true.

One solution is to go through the entire comment (which I haven't), in order to update it and bring it up to date. This still leaves us having to maintain both.

Another solution: delete the comment. I suspect this will be a little bad as we probably need to have some kind of crate comment, thus

Solution 3: Remove most of it, referring to `README.md` for use and configuration, leaving any information that has to do with the actual code.
