### ISSUE TITLE
RFC: What can be a template?

### ISSUE THREAD

**Issue by killercup** [cargo-generate/cargo-generate#47]
## Context

When executing cargo-generate a user needs to pass an identifier for the template they want to generate a project from.

## Questions

What can be such template identifiers?

How can we extract a cargo-generate compatible template from them?

## Possibles solutions

One or more of

- git repo
- directory
- crate
- sub dir in a repo

**Comment by durka** [comment]
If downloading from Github is going to be common, it seems like a good idea to support `username/repo` syntax instead of the full URL.

Also, what about gists?

**Comment by mmstick** [comment]
No reason not to support all the possible solutions.

**Comment by anirudhb** [comment]
I think if it has a Cargo.toml, it is a template.

**Comment by durka** [comment]
So I could then just cargo-generate any crate, and it would download it and
replace the author's name with mine? That seems kinda weird...

**Comment by anirudhb** [comment]
Not like that! 😅
I was thinking if it _wasn't_ published to crates.io, then we could do that...

**Comment by killercup** [comment]
> I think if it has a Cargo.toml, it is a template.

People want to use this for mdbook repos too: #14

**Comment by rahul-thakoor** [comment]
Yes, in this case having a book.toml makes it a template. 

Are we able to pass in local git repos? This could be helpful when creating and testing templates.

**Comment by softprops** [comment]
Porteurbars went with local directly , GitHub, and raw gitburls https://github.com/softprops/porteurbars/blob/master/src/git.rs#L10

Local dirs are especially useful for local fast testing of a new template

**Comment by skade** [comment]
I would like to register interest in "subdirectory of a repos". Our use case is managing a number of assignments in one git respos and we would like to ship starter templates along with them in subdirectories.

**Comment by taurr** [comment]
How is "crate as a template" supposed to work?
Do we need it?

**Comment by sassman** [comment]
One way I imagine it to work is downloading from crates.io and the. Treating it similar as a local `--path` template folder.

Not sure if we need it, because I believe that a crate that is only a template might even not compile and there for might even be not publishable.

I would say we threat this issue as solved unless some folks have a real use case for crate as template.

**Comment by taurr** [comment]
>Not sure if we need it, because I believe that a crate that is only a template might even not compile and therefore might even be not publishable.

>I would say we threat this issue as solved unless some folks have a real use case for crate as template.

Wholeheartedly agreed!
