### ISSUE TITLE
Rhai variable extension doesn't work

### ISSUE THREAD

**Issue by GabrielDertoni** [cargo-generate/cargo-generate#471]
I was testing cargo generate with Rhai scripting and reading the source code on this repo when I noticed that the variable extension should't work at all. In the source code `src/hooks/mod.rs` only an immutable reference to the Liquid object was handed to the code that interacts with rhai scripting. In the current implementation you should only be able to set and get Liquid variables inside the same Rhai script, but not set a variable that can be used in the Liquid template expansion. This also means I could't make the hooks example work!

I have already implemented a simple solution but I have never done an Open Source contribution and would like some comments on this topic. Maybe a have just missed something!

**Comment by taurr** [comment]
Nice catch, and welcome as a contributor.

I myself did my first OS contribution back in february - coincidentally also on this project 😆
