### ISSUE TITLE
alpine musl ssl package leads to seg fault

### ISSUE THREAD

**Issue by byteshiva** [cargo-generate/cargo-generate#499]
Unable to load   /usr/local/cargo/cargo-generate.toml?
```
uname -a             
Linux  5.10.0-8mx-amd64 #1 SMP Debian 5.10.46-4~mx19+1 x86_64 Linux
```
**Error**
```
cargo generate --git https://github.com/rustwasm/wasm-pack-template.git --name wasm-game-of-life
 Unable to load config file: /usr/local/cargo/cargo-generate.toml
```

```
cargo-generate --version      
cargo-generate 0.11.0
```

**Comment by sassman** [comment]
is there a file a `/usr/local/cargo/cargo-generate.toml` on your machine?

**Comment by byteshiva** [comment]
I don't see cargo-generate.toml at `/usr/local/cargo`

```
/work $ set | grep HOME
CARGO_HOME='/usr/local/cargo'
HOME='/home/wasm-pack'
RUSTUP_HOME='/usr/local/rustup'
```


```
/work $ cd  /usr/local/cargo
/usr/local/cargo $ ls 
bin       env       registry
/usr/local/cargo $ 
```

**Comment by sassman** [comment]
Just now I'm realising that this below is actually not an error. It's just a regular info message that the file does not exist, but it will not fail the program.

>  Unable to load config file: /usr/local/cargo/cargo-generate.toml

So my question is, what is the final error message you are getting?

**Comment by byteshiva** [comment]
Here error log:
```
/work $  cargo generate --git https://github.com/rustwasm/wasm-pack-template.git --name wasm-game-of-life 
 Unable to load config file: /usr/local/cargo/cargo-generate.toml
Segmentation fault

```

**Comment by sassman** [comment]
oh wow! What linux distro and version it is that you use? I need to produce that.. a seg fault is rare..

**Comment by byteshiva** [comment]
uname -a 
```
Linux 5.10.0-8mx-amd64 #1 SMP Debian 5.10.46-4~mx19+1 x86_64 Linux
```

**Comment by byteshiva** [comment]
I'm using `docker` to run the `cargo generate ` 

I've uploaded it to docker hub. 
```
https://hub.docker.com/r/byteshiva/wasm-pack-caro-generate
```

You can use the following command to reproduce the errors.

```
docker run -it  byteshiva/wasm-pack-caro-generate:0.10.1 /bin/sh
/work $ cargo generate --git https://github.com/rustwasm/wasm-pack-template.git --name wasm-game-of-life 
 Unable to load config file: /usr/local/cargo/cargo-generate.toml
Segmentation fault
/work $ 

```

**Comment by sassman** [comment]
> Linux Distro : MX Linux 19.1,

Unfortunately it seems there is no docker image already for MX Linux. So reproduction might take me a while.


> I'm using docker to run the cargo generate

But could you pls try to run `cargo-generate` natively not within a docker container?

**Comment by sassman** [comment]
> I've uploaded it to docker hub.
> https://hub.docker.com/r/byteshiva/wasm-pack-caro-generate

I have tried your docker image, with the same results. I wonder how did you install cargo generate in there?

I have made it work inside this image with using the latest [cargo-generate binary](https://github.com/cargo-generate/cargo-generate/releases/download/v0.11.1/cargo-generate-v0.11.1-x86_64-unknown-linux-musl.tar.gz)

like this:

```sh
cd /tmp
wget https://github.com/cargo-generate/cargo-generate/releases/download/v0.11.1/cargo-generate-v0.11.1-x86_64-u
nknown-linux-musl.tar.gz
tar xzf cargo-generate-v0.11.1-x86_64-unknown-linux-musl.tar.gz
./cargo-generate generate --git https://github.com/rustwasm/wasm-pack-template.git --name wasm-game-of-life
 Unable to load config file: /usr/local/cargo/cargo-generate.toml
 Generating template ...
[ 1/12]   Done: .appveyor.yml
[ 2/12]   Done: .gitignore
[ 3/12]   Done: .travis.yml
[ 4/12]   Done: Cargo.toml
[ 5/12]   Done: LICENSE_APACHE
[ 6/12]   Done: LICENSE_MIT
[ 7/12]   Done: README.md
[ 8/12]   Done: src/lib.rs
[ 9/12]   Done: src/utils.rs
[10/12]   Done: src
[11/12]   Done: tests/web.rs
[12/12]   Done: tests
 Moving generated files into: `/tmp/wasm-game-of-life`...
 Done! New project created /tmp/wasm-game-of-life
```

Also what I've noticed in your image everything below `/usr/local/cargo/` is owned by `root` but the user your are defaultly using is `uid=1000(wasm-pack) gid=1000(wasm-pack)`

That leads to an issue when installing things via `cargo install`. For example I was not able to install `cargo-generate` freshly.

**Comment by byteshiva** [comment]
The gist below contains  `Dockerfile` and `build.sh` to create a new cargo-generate and et al Image.

https://gist.github.com/byteshiva/1ff650c64f401a330d9642c2b3294c26

**Comment by sassman** [comment]
I've taken this gist of yours and adjusted the way how to install cargo-generate to get it working.

```diff
@@ -16,7 +16,7 @@ RUN apk add --no-cache \
     && cargo install wasm-pack --version=${WASM_PACK_VERSION} \
     && rustup target add wasm32-unknown-unknown \
     && chmod -R 777 /usr/local/cargo/registry \
+    && cargo install cargo-generate --features vendored-openssl
-    && cargo install cargo-generate

 ENV USER=wasm-pack
```

Since this works, we know now it's an ssl related issue.

I found [this thread](https://users.rust-lang.org/t/sigsegv-with-program-linked-against-openssl-in-an-alpine-container/52172/6) about pretty much the same issue.

They suggest to use `RUSTFLAGS=-C target-feature=-crt-static` to avoid dynamically linked musl packages.

You may give it a shot.

**Comment by byteshiva** [comment]
it worked after adding `+    && cargo install cargo-generate --features vendored-openssl`

I've pushed the image to the docker hub.

```
docker run --rm -v "$(pwd):/work" -u $(id -u):$(id -g) byteshiva/wasm-pack-caro-generate:0.10.1 cargo-generate generate --git https://github.com/rustwasm/wasm-pack-template.git --name wasm-game-of-life
```
