### ISSUE TITLE
forcing git initialisation by a new flag `--force-git-init`

### ISSUE THREAD

**Issue by taladar** [cargo-generate/cargo-generate#516]
It seems cargo-generate ignores any and all attempts to allow for git initialization when the target directory is already inside an existing git repository.

I use git for the config files in my home directory and so it seems I can not create any git initialized repositories with cargo-generate anywhere in my home.

**Comment by sassman** [comment]
That's an interesting issue.

> I use git for the config files in my home directory

Are you not using a `.dotfiles` folder where the git checkout of your dot files lives, and then symlink e.g. `ln -s ~/.dotfiles/.bashrc ~/` it over into your home?

**Comment by taladar** [comment]
No, I am not using a .dotfiles folder and symlinking the files since it has been working fine without that extra step for years.

**Comment by sassman** [comment]
ok. Just to be sure if I have understood it all right: there is a `.git` folder in your `$HOME`?

**Comment by taladar** [comment]
Yes, there is a .git folder in $HOME

**Comment by sassman** [comment]
I tried to call `cargo generate` in a folder that has a `.git` directory without any issues.
Also I tried the same directly in $HOME and this worked too.

Could you please provide me some reproduction steps? Ideally some paste steps so that I can understand your problem in all detail?

**Comment by taladar** [comment]
Try this
```
mkdir /tmp/test1
cd /tmp/test1
cargo generate --name test1 (and other options, any template should do)
ls -l /tmp/test1/test1/.git
mkdir /tmp/test2
cd /tmp/test2
git init
cargo generate --name test2 (otherwise identical options as before)
ls -l /tmp/test2/test2/.git
```

That last ls should fail since there is not .git

Presumably the culprit is this code in src/git.rs

```
pub fn init(project_dir: &Path, branch: &str) -> Result<Repository> {
    Repository::discover(project_dir).or_else(|_| {
        let mut opts = RepositoryInitOptions::new();
        opts.bare(false);
        opts.initial_head(branch);
        Repository::init_opts(project_dir, &opts).context("Couldn't init new repository")
    })
}
```

which does not initialize the git repository if one is discovered, see

https://docs.rs/git2/latest/git2/struct.Repository.html#method.discover

> Attempt to open an already-existing repository at or above path
>
> This starts at path and looks up the filesystem hierarchy until it finds a repository.

**Comment by sassman** [comment]
> That last ls should fail since there is not .git

That might be a bit confusing, but `cargo-generate` will initialise an empty git repo after the template is created.
The only case where it would **NOT** do this is when:
- you use either the flag `--init` or 
- when the folder you are calling `cargo-generate` from a folder that is already under git (has a `.git` folder inside)

I hope that sheds some light on the mechanics that might be a bit confusing.

**Comment by taladar** [comment]
They are not confusing at all. I understand what cargo generate does. I just consider it a missing feature that there is no way to force override the auto-magic behaviour you mention in your second point.

For that matter, what I would consider a bug is that you can specify --vcs git and end up with no git repository because the auto-magic behaviour takes precedence over the explicit parameter.

**Comment by sassman** [comment]
I get your point.

So would it be more intuitive that the git init happens by default in all cases and there would be a flag to disable it on demand?

Or would you be fine with a flag that force initialize a git repo, no matter if the dir you start calling is already under git?

IMO the defaults right now cover common cases. And a force flag would be sufficient to cover your case. But open for suggestions.

**Comment by sassman** [comment]
so specifically something like this is what I was talking about:

```sh
# illustrating --force-git-init 
cargo generate --path ~/templates/cli-template --force-git-init --name foo

# or with --git
cargo generate --git sassman/cli-template-rs --force-git-init --name foo
```

**Comment by taladar** [comment]
A force flag would be fine for my use-case.
