### ISSUE TITLE
template sub directory error lacks context

### ISSUE THREAD

**Issue by ChristopherBiscardi** [cargo-generate/cargo-generate#526]
When using templates in sub directories, if the template name (the sub-dir name) doesn't exist the error "No such file or directory" is provided without any additional context. The lack of context makes it hard to know why the error occurred.

```
❯ cargo generate rust-adventure/generate serverless
⚠️   Unable to load config file: /Users/chris/.cargo/cargo-generate.toml
Error: No such file or directory (os error 2)
```

In this case it is because the sub-dir `serverless` doesn't exist in the template repo.

**Comment by sassman** [comment]
good catch! Makes totally sense to be here a bit more verbose.
Maybe something of an error message like:

`Error: not abele to find folder "serverless" in repository "rust-adventure/generate"`

would that make sense?

**Comment by ChristopherBiscardi** [comment]
yeah, that makes sense to me. Might be even better if `rust-adventure/generate` was a link?

**Comment by sassman** [comment]
> yeah, that makes sense to me. Might be even better if rust-adventure/generate was a link?

I suggest to show the full qualified URL of the repo (so either the ssh or the https url that was used).
