### ISSUE TITLE
Using the shorthand org/repo with a non-existing org results in an authentication error

### ISSUE THREAD

**Issue by ChristopherBiscardi** [cargo-generate/cargo-generate#527]
When using the github shorthand and using an org that doesn't exist (such as mistyping a - or similar), the error shown is a git remote authentication error.

```
❯ cargo generate someorgihopedoesntexist/generate netlify-function
⚠️   Unable to load config file: /Users/chris/.cargo/cargo-generate.toml
⚠️   Favorite someorgihopedoesntexist/generate not found in config, using it as a git repo url
Error: ⛔   Git Error: remote authentication required but no callback set; class=Http (34); code=Auth (-16)
```

This error lead me to believe there was something wrong with my git or ssh config, not a typo, and could use some additional context if possible.

**Comment by sassman** [comment]
yeah, this is [already fixed](https://github.com/cargo-generate/cargo-generate/pull/521) and will come in v0.13.0 very soon.
