### ISSUE TITLE
dyld: Symbol not found: _EVP_aes_128_cbc

### ISSUE THREAD

**Issue by binnz** [cargo-generate/cargo-generate#528]
hi, after install cargo-generate, below error occurs.
```
└─[$]> ./cargo-generate
dyld: Symbol not found: _EVP_aes_128_cbc
  Referenced from: /Users/binnz/.cargo/bin/./cargo-generate
  Expected in: flat namespace
 in /Users/binnz/.cargo/bin/./cargo-generate
```

OS: macOS 11.4 20F71 x86_64
Host: MacBookPro17,1
Kernel: 20.5.0

rustc 1.58.0-nightly (936f2600b 2021-11-22)

**Comment by sassman** [comment]
@binnz Am I right assuming you've installed it via `cargo install cargo-generate` or did you download the binaries?

**Comment by binnz** [comment]
> @binnz Am I right assuming you've installed it via `cargo install cargo-generate` or did you download the binaries?

i use cargo install cargo-generate

**Comment by sassman** [comment]
Could you try to switch to the stable channel and redo? 
I tried to reproduce it on my M1 but, it all works as usual.

**Comment by sassman** [comment]
But this very error message, a missing symbol that sounds to me like a crypto function (_EVP_aes_128_cbc)

> dyld: Symbol not found: _EVP_aes_128_cbc

Happens also to others on the web and seems to relate to a missing / faulty OpenSSL installation.

see
- http://erlang.org/pipermail/erlang-questions/2016-November/090827.html
- https://github.com/nodegit/nodegit/issues/1622
