### ISSUE TITLE
Might need to enable GitHub Pages in the repo settings

### ISSUE THREAD

**Issue by joshrotenberg** [cargo-generate/cargo-generate#539]
https://github.com/cargo-generate/cargo-generate/pull/519 added the book and the deploy action. 

Looks like the action is running correctly as I see content in the `gh-pages` [branch](https://github.com/cargo-generate/cargo-generate/tree/gh-pages) but the link to the guide gives me a [404](https://cargo-generate.github.io/cargo-generate/index.html). Is it possible that pages aren't enabled?

Edit: should be here: https://github.com/cargo-generate/cargo-generate/settings/pages

**Comment by sassman** [comment]
@joshrotenberg, you were right. the message there was a bit misleading but once the save button was pressed it started to deploy the `gh-pages` branch

**Comment by sassman** [comment]
Thank you very much for all your effort! That was great work, and looks very nice now!
