### ISSUE TITLE
cargo install failed on ubuntu 20.04.3 LTS due to `lto`

### ISSUE THREAD

**Issue by PinkJohnOfUs** [cargo-generate/cargo-generate#541]
Installing cargo-generate doesn't work on:

**Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
rustc 1.58.1 (db9d1b20b 2022-01-20)
cargo 1.58.0 (f01b232bc 2022-01-19)**

How to reproduce:
`cargo install cargo-generate` 

output:
`   Compiling cargo-generate v0.13.0
error: failed to compile `cargo-generate v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-installPi1D2T`

Caused by:
  could not compile `cargo-generate`

Caused by:
  process didn't exit successfully: `rustc --crate-name cargo_generate --edition=2021 /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.13.0/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=241894174fbd213e -C extra-filename=-241894174fbd213e --out-dir /tmp/cargo-installPi1D2T/release/deps -L dependency=/tmp/cargo-installPi1D2T/release/deps --extern anyhow=/tmp/cargo-installPi1D2T/release/deps/libanyhow-d3a5197222203f4e.rlib --extern cargo_generate=/tmp/cargo-installPi1D2T/release/deps/libcargo_generate-2efbd5cd0895c498.rlib --extern console=/tmp/cargo-installPi1D2T/release/deps/libconsole-33bb50bfd7b7d7cb.rlib --extern dialoguer=/tmp/cargo-installPi1D2T/release/deps/libdialoguer-dac552e13321e4be.rlib --extern dirs=/tmp/cargo-installPi1D2T/release/deps/libdirs-f2e59bd997d8fa2a.rlib --extern git_config=/tmp/cargo-installPi1D2T/release/deps/libgit_config-9744ae79e9a84b21.rlib --extern git2=/tmp/cargo-installPi1D2T/release/deps/libgit2-87a1b8ce867f76e6.rlib --extern heck=/tmp/cargo-installPi1D2T/release/deps/libheck-7cfdd743940b09ad.rlib --extern home=/tmp/cargo-installPi1D2T/release/deps/libhome-dda3f976a70fe7b3.rlib --extern ignore=/tmp/cargo-installPi1D2T/release/deps/libignore-0985891f5e4a46a4.rlib --extern indicatif=/tmp/cargo-installPi1D2T/release/deps/libindicatif-969260ea91152c04.rlib --extern libgit2_sys=/tmp/cargo-installPi1D2T/release/deps/liblibgit2_sys-2604cba3b737db3e.rlib --extern liquid=/tmp/cargo-installPi1D2T/release/deps/libliquid-a29cf2e2e081f52b.rlib --extern liquid_core=/tmp/cargo-installPi1D2T/release/deps/libliquid_core-f73415ac7ab55100.rlib --extern liquid_derive=/tmp/cargo-installPi1D2T/release/deps/libliquid_derive-126be2eeaa0f31d4.so --extern liquid_lib=/tmp/cargo-installPi1D2T/release/deps/libliquid_lib-0d177fd3d6dc1737.rlib --extern path_absolutize=/tmp/cargo-installPi1D2T/release/deps/libpath_absolutize-cf1da7f4113f7b1c.rlib --extern regex=/tmp/cargo-installPi1D2T/release/deps/libregex-398d50b8eb53d2be.rlib --extern remove_dir_all=/tmp/cargo-installPi1D2T/release/deps/libremove_dir_all-d1c8183d2f2eb4e2.rlib --extern rhai=/tmp/cargo-installPi1D2T/release/deps/librhai-4bb3c175d907bf2b.rlib --extern sanitize_filename=/tmp/cargo-installPi1D2T/release/deps/libsanitize_filename-fd3c4742d9facc33.rlib --extern semver=/tmp/cargo-installPi1D2T/release/deps/libsemver-2b1d0ee6be5bc56e.rlib --extern serde=/tmp/cargo-installPi1D2T/release/deps/libserde-ab0a4fc83781f371.rlib --extern structopt=/tmp/cargo-installPi1D2T/release/deps/libstructopt-3f62a1d69bb9bff3.rlib --extern tempfile=/tmp/cargo-installPi1D2T/release/deps/libtempfile-8e4fabd97a20c1b6.rlib --extern thiserror=/tmp/cargo-installPi1D2T/release/deps/libthiserror-abe150936e3bd32d.rlib --extern toml=/tmp/cargo-installPi1D2T/release/deps/libtoml-1fdfbfae3ef383dc.rlib --extern url=/tmp/cargo-installPi1D2T/release/deps/liburl-bb229dd6a482c602.rlib --extern walkdir=/tmp/cargo-installPi1D2T/release/deps/libwalkdir-de54131859195ec7.rlib --cap-lints allow -L native=/tmp/cargo-installPi1D2T/release/build/libgit2-sys-1ad4f379fe56ab7d/out/build -L native=/tmp/cargo-installPi1D2T/release/build/libssh2-sys-3455f7c702df82b0/out/build -L native=/tmp/cargo-installPi1D2T/release/build/libz-sys-7d6e231a3b1ec9d7/out/lib -L native=/tmp/cargo-installPi1D2T/release/build/libz-sys-7d6e231a3b1ec9d7/out/lib` (signal: 9, SIGKILL: kill)
`

**Comment by sassman** [comment]
could you please check that you have 2 packages installed: `pkg-config` and `libssh-dev` ?

**Comment by PinkJohnOfUs** [comment]
yes I have this packages installed. I've tested it within a container there it works. But within a vm (multipass) it doesn't work.
Here the complete steps to reproduce:
1. multipass launch -d 11G -n testvm
2. ubuntu@testvm$ apt install build-essential pkg-config libssl-dev
3. ubuntu@testvm$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
4. ubuntu@testvm$ source ./cargo/env
5. ubuntu@testvm$ cargo install cargo-generate

**Comment by sassman** [comment]
Thanks for the steps, I was not aware of `multipass` yet. Nice tool.
So finally I can confirm the issue. 

It is somehow related to link time optimization. For example when skipping link time optimization as below it installs just fine:
```sh
CARGO_PROFILE_RELEASE_LTO=thin cargo install -f cargo-generate
```

I must assume that is some sort of regression in `rustc` specific to the `ubuntu` packages in 20.04, but tbh I have no real idea.

**Comment by PinkJohnOfUs** [comment]
Thank you this workaround works for me! 
![multipass](https://user-images.githubusercontent.com/49363983/153222636-aa30c8a5-a613-48dd-90c6-54c3bc64c631.png)
u
