### ISSUE TITLE
Silently ignoring files with `{}` around `{{variable}}`

### ISSUE THREAD

**Issue by zeenix** [cargo-generate/cargo-generate#549]
After an entire day of trying to debug why cargo-generate simply ignores one of my files, it turns out that it was because it used a variable substitution next to a `{`. Here is my simple reproducer:

```
❯ cargo generate --git zeenix/cargo-generate-test --name blah -d replace_me=replaced
⚠️   Unable to load config file: /home/zeenix/.cargo/cargo-generate.toml
replace_me => 'replaced'
🔧   Generating template ...
[1/6]   Done: .gitignore
[2/6]   Done: Cargo.lock
[3/6]   Done: Cargo.toml
[4/6]   Done: LICENSE
[6/6]   Done: src
🔧   Moving generated files into: `/tmp/blah`...
💡   Initializing a fresh Git repository
✨   Done! New project created /tmp/blah
```

Notice how the `main.rs` is simply ignored and there's nothing reported about that file. I understand if they is a known limitation that can't be fixed easily but then cargo-gen should report that or error out.

**Comment by sassman** [comment]
Thanks for the interesting bug report.

Step `[5/6]` is probably the file `src/main.rs`, but it's not listed.
I would also agree that showing something like this, would help to be more aware of the situation:

```raw
[3/6]   Done: Cargo.toml
[4/6]   Done: LICENSE
[5/6]   Skipped: src/main.rs
[6/6]   Done: src
```

**Comment by zeenix** [comment]
> Step `[5/6]` is probably the file `src/main.rs`, but it's not listed.

Oh, I somehow didn't even notice a number missing. :)

> I would also agree that showing something like this, would help to be more aware of the situation:

Definitely better than silently ignoring but it'd good to also be told why and some clue. Maybe it could only be available in `verbose` mode and people can enable that to find out reasons when they see a file being ignored?

**Comment by sassman** [comment]
> Definitely better than silently ignoring but it'd good to also be told why and some clue. Maybe it could only be available in verbose mode and people can enable that to find out reasons when they see a file being ignored?

I totally agree, but we have to see if the template lib (liquid) would give us any insights here.
I'm suspecting that in `src/main.rs` the triple curly braces in `{{{ variable }}}` are the problem, so liquid does not recognize it as a valid thing to be replaced. 
If that is true, then it will become pretty hard to find out such issues. Because `cargo-generate` would never know if that is done by mistake or done on purpose in the template.

**Comment by zeenix** [comment]
> > Definitely better than silently ignoring but it'd good to also be told why and some clue. Maybe it could only be available in verbose mode and people can enable that to find out reasons when they see a file being ignored?
> 
> I totally agree, but we have to see if the template lib (liquid) would give us any insights here.

Ah OK. I hope it does. :)

> I'm suspecting that in `src/main.rs` the triple curly braces in `{{{ variable }}}` are the problem, so liquid does not recognize it as a valid thing to be replaced.

Most likely. FWIW, my original issue was a use statement actually which involved separate `{{{` and `}}}`. Something like this:

```rust
use some_mod::{{{replaced}}, {{another_replaced}}};`
```

> If that is true, then it will become pretty hard to find out such issues. Because `cargo-generate` would never know if that is done by mistake or done on purpose in the template.

:(

**Comment by sassman** [comment]
There might be a silly solution to the problem, maybe try out this:

```rust
use some_mod::{{ replaced | prepend: "{" }}, {{ another_replaced | append: "}" }};
```

**Comment by taurr** [comment]
@sassman It seems that if `Liquid` doesn't like the file's syntax for 1 reason or another, it will just not handle the file! `cargo-generate` wont know of the problem, so we can't even warn about it.

Your "solution" to the problem above actually seems pretty solid, and is a nice way of "escaping" in these situations.

It's quite similar to the problem of handling github workflow files - I've written a little discussion post on the issue.

My recomendation: close this issue as is has a known workaround, add to the discussion...
