### ISSUE TITLE
Support subdirectories as templates

### ISSUE THREAD

**Issue by Timmmm** [cargo-generate/cargo-generate#555]
E.g. https://github.com/thedodd/trunk/tree/master/examples/yew

Unlike cloning a repo and editing `Cargo.toml`, downloading a subdirectory of a repo is quite a pain. At least I don't know how to do it easily. So it would make cargo-generate a lot more useful.

**Comment by sassman** [comment]
Hi @Timmmm 

I'm glad you're asking because this is already a supported use case.

You can read more about it in the [docs](https://cargo-generate.github.io/cargo-generate/usage.html#templates-in-subfolders) 

So for this given example try out:
```sh
cargo generate --git thedodd/trunk examples/yew
```

**Comment by Timmmm** [comment]
Aha brilliant, thank you!
