### ISSUE TITLE
test authors substitution

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#58]

**Comment by b-ramsey** [comment]
Hi, I'd like to have a go at this issue. Just a couple of queries before I get started:

Any rules associated with structuring your tests. From what I can tell it is all just in the basics.rs test file. Should the new tests be placed in here as well?

From viewing the code that is associated with this action I can see that test cases should cover the priorities of the sources, and all methods can be used for substitution. Have I missed any paths?

**Comment by ashleygwilliams** [comment]
hey @b-ramsey - i think your understanding sounds right! let me know if you have any other questions! the function that collect author data is here: https://github.com/ashleygwilliams/cargo-generate/blob/master/src/cargo.rs#L8

**Comment by taurr** [comment]
@ashleygwilliams, @sassman : is this even an issue anymore?
