### ISSUE TITLE
Support for system commands

### ISSUE THREAD

**Issue by v-n-suadicani-issuu** [cargo-generate/cargo-generate#596]
This is something provided by other templating libraries, such as cookiecutter. There are plenty of times it might be useful to run system scripts for a template.

It could be provided by exposing the [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html) struct in the standard library to the Rhai scripts somehow. That would allow you to use the placeholder variables and all to decide whether to run some system command.

This is obviously a security risk too, but presumably people are creating a template because they are going to run `cargo` on it - in which case a malicious `build.rs` could do whatever it wants anyway. So I don't think this really increases the security risk much, if at all.

**Comment by taurr** [comment]
Except that `cargo` is not run on the template by `cargo-generate`, so the developer has the possibility (and some would say responsibility) to check the code before actually trying to build it.

I do agree that this would be nice, but I would have a dialog confirming whether it is OK to execute the commands before actually doing it - as well as a commandline option to resolve the dialog beforehand (so the expansion doesn't ask but just executes/denied as requested)

**Comment by sassman** [comment]
> I do agree that this would be nice, but I would have a dialog confirming whether it is OK to execute the commands before actually doing it

I agree. At least for me as a user running arbitrary code on my machine provided by templates from the internet causes quite a bit of discomfort.

But of course, everyone can vote on this in order to express the usefulness.

**Comment by v-n-suadicani-issuu** [comment]
>I would have a dialog confirming whether it is OK to execute the commands before actually doing it

I think that sounds perfectly reasonable - if integrated in the Rhai scripting, I suppose the command function could return an `Option` of [`Output`](https://doc.rust-lang.org/std/process/struct.Output.html), with it being set to `None` if the user refused to run the command. Then the script could handle that somehow if needed.

**Comment by v-n-suadicani-issuu** [comment]
@taurr @sassman Took a stab at implementing this in #598, do let me know what you think.

**Comment by sassman** [comment]
looks very good and it's now released in `v0.14.0` but I just realized that we miss proper docs for the feature as in the mdbook.
