### ISSUE TITLE
Renaming a folder destination

### ISSUE THREAD

**Issue by taqtiqa-mark** [cargo-generate/cargo-generate#603]
Thanks for all the effort put into `cargo generate` and for making it open source.
We have a use case where we'd like to rename the subfolder - the following is how we understand to accomplish this via `cargo generate` as it stands today:
 
```bash
cargo generate some/template base
cd base
for i in a b c d;
do
  mkdir $i
  cd $i
  cargo generate --init some/template subset
done
```

However this is only convenient when you are creating `a`, `b`, `c` and `d` at the same time.  

When `a`, `b`, `c` and `d` arise over some months the user has to carefully consult the `cargo-generate` docs - our template is no longer self contained.

Ideally we'd like the user to be able to run `cd base; cargo generate some/template subset`, and have one of the prompts be: "What should this template be named?"
The user responding `c` would be equivalent to:

```bash
mkdir c
cd c
cargo generate --init some/template subset
```

Hopefully we haven't missed some setting or option?
Is that functionality in scope?

**Comment by sassman** [comment]
Hey @taqtiqa-mark,

Thanks for your interest.

Just to be clear that I got it all right. `some/template/a` is a Self contained template on it's own, right? Same for b c and d?

**Comment by taqtiqa-mark** [comment]
Hi @sassman, thanks for the prompt response.

The self contained templates are `some/template/base`, `some/template/subset`.

For the `subset` template, once the user has provided their responses to the `placeholders` prompts, it would become (in the example) `./base/a`, `./base/b`, etc.

Hopefully that clarifies.  I believe the workaround I set out will work (still in development), but it'd be nice to drop the `mkdir`, `cd` and `--init`.

**Comment by sassman** [comment]
I see, 

but to replace this:
```sh
mkdir c
cd c
cargo generate --init some/template subset
```

you could simply do the following, (both is equivalent):
```
cargo generate some/template subset --name c
```

**Comment by sassman** [comment]
But the double templating,

first `cargo generate some/template base`, then
```sh
cd base
for i in a b c d;
do
  mkdir $i
  cd $i
  cargo generate --init some/template subset
done
```

is indeed not straight supported.

**Comment by taqtiqa-mark** [comment]
> you could simply do the following, (both is equivalent):
> 
> `cargo generate some/template subset --name c`

Nice, obviously I missed that.  Is it possible to setup the `cargo-generate.toml` such that the user doesn't have to remember to do that?

> But the double templating, ... is indeed not straight supported.

That's OK.  I don't see a problem with a user doing:

```bash
cargo generate some/template base
cd base
cargo generate some/template subset
cargo generate some/template subset
cargo generate some/template subset
cargo generate some/template subset
....
```

As long as they are prompted rather than have to memorize cargo-generate options - that my main reservation - I know I won't recall `--name c` etc. :)

**Comment by sassman** [comment]
Maybe @taurr has a creative idea on how to solve this with a rhai pre-hoook script?

**Comment by taurr** [comment]
There's always the new `system` command - PR #598, part of newest release ?
As it allows invoking command line tools, you could do this interactively and script driven 😄

**Comment by taqtiqa-mark** [comment]
We'll likely adopt a lighter weight, more flexible solution, with the added benefit of not having to learn a new rust-centric language stack just to rename a file/folder.
