### ISSUE TITLE
Doc: What templating language does cargo generate use?

### ISSUE THREAD

**Issue by taqtiqa-mark** [cargo-generate/cargo-generate#607]
What templating language does cargo generate use?

**Comment by taqtiqa-mark** [comment]
OK, this is information is buried at the end of a paragraph, half way down the templates page.

Would you accept a PR moving this information:

1. to the README.md and
2. to the [introduction page](https://cargo-generate.github.io/cargo-generate/templates/index.html)

**Comment by taurr** [comment]
I for one would welcome the PR - especially if you also put a link to the scripting language `rhai`, which is also utilized as part of the templates

**Comment by taqtiqa-mark** [comment]
Per this [comment](https://github.com/cargo-generate/cargo-generate/issues/618#issuecomment-1145418673) - we don't have bandwidth to help flesh out any additional functionality in this issue.
