### ISSUE TITLE
failing to compile

### ISSUE THREAD

**Issue by letto4135** [cargo-generate/cargo-generate#633]
Recent change to hooks/mod.rs 10 days ago, I believe it may be causing an issue. 
I'm on a mac m1

stable-x86_64-apple-darwin unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)
nightly-x86_64-apple-darwin unchanged - rustc 1.63.0-nightly (420c970cb 2022-06-09)

The error happens no matter whether I'm on stable or nightly.

error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-generate-0.14.0/src/hooks/mod.rs:19:6
   |
19 | impl<F: FnOnce()> CleanupJob<F> {
   |      ^
20 |     pub const fn new(f: F) -> Self {
   |     ------------------------------ function declared as const here
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information

Was able to install 0.13.1 just fine.

**Comment by letto4135** [comment]
After a long and annoying journey I found out that I had two versions of rust installed, no idea where the second one came from. Cargo was being ran from the second version, rustup from the version I needed. I eventually found out after installing the 0.13.1 version of this and it told me I wasn't using rustup which I knew I was.

**Comment by sassman** [comment]
Thanks for sharing this.
