### ISSUE TITLE
Feature request: Set default VCS from within templates

### ISSUE THREAD

**Issue by laundmo** [cargo-generate/cargo-generate#635]
It would be nice if it was possible to make templates default to a different or no VCS initialisation. In my case this would be useful for a "minimal" template meant for messing around inside. Could also be useful for templates which are meant to be a smaller part of a larger vcs repository.

As a workaround I tried to delete the initialised vcs repository from rhai, but that doesn't work as rhai scripts run before vcs initalisation.

**Comment by sassman** [comment]
Hey, for rhai scripts there are pre and post hook scripts. 
A post hook script should provide what you need.

**Comment by laundmo** [comment]
I tested with a post hook script. It prints before the VCS initialisation, and cannot delete the vcs folder since it doesn't exist yet.

**Comment by sassman** [comment]
Ok, I think that is probably a bug or a debatable issue of the post hooks. They should run after all, at the very end.

However, coming back to your original issue, your wanted to have your project generated, without a `.git` entry, so no `git init` in the final result folder, right?

Then have you tried out the `--init` command-line argument yet?

```plain
        --init
            Generate the template directly into the current dir. No subfolder will be created and no vcs is initialized
```

This is actually meant for this sort of thing you've mentioned:

> Could also be useful for templates that are meant to be a smaller part of a larger vcs repository.

The only caveat is: the whole template is generated into your current folder (`$CWD`).

But more generically speaking the parameters:

* `--init-vcs=git|hg` like current behavior, it `git init` ran after all (with being extendable to e.g. mercurial and others)
* `--skip-init-vcs` a flag to disable the current initialization behavior

Might address your point more accurately.

**Comment by laundmo** [comment]
Actually, no commandline flag would address my point properly, unless there is a way to set them from the template config.

I want to be able to set the default for vcs initialisation as a template author for the template I'm creating, not toggle it off once when running the command.

**Comment by taurr** [comment]
Do remember that this should also be available under the **favorites** settings in the global `cargo-generate.toml`

**Comment by taurr** [comment]
> Ok, I think that is probably a bug or a debatable issue of the post hooks. They should run after all, at the very end.

Please see #637 - there's a reason.
There's also a small issue with post hook printing comming *before* the processing - there's an issue on it alreaty
