### ISSUE TITLE
Feat: when pointing to a multi-template repo, it should be possible to explicitly specify the default template

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#636]
When using `cargo-generate` with a multi template repository, `cargo-generate` creates a `choice` prompt for the user to select a 
template to expand.

It would help on usability if it was possible to influence this prompt.

1) It should be possible to specify the default selected template.
2) It would be nice if the template author could specify the sorting order, or specify the list of templates manually.

**Comment by sassman** [comment]
> When using cargo-generate with a multi template repository, cargo-generate creates a choice prompt for the user to select a
template to expand.

The choices presented to the users, should be based on the first level of directories in the template repository?
