### ISSUE TITLE
ci: no reason to run fmt and clippy on all matrix targets

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#644]
We can speed up CI by skipping `cargo fmt` and `cargo clippy` from all but 1 target.

`clippy` already checks for all features and targets.

`fmt` yields the same result for all targets.

**Comment by sassman** [comment]
the thing is, that different target platforms yields different results.

**Comment by sassman** [comment]
> If they do, I'm pretty much doomed as a dev - I only have 1 platform, and formatting the code differently for different targets is pretty hard with a single code base.

Here you go:
https://github.com/cargo-generate/cargo-generate/actions/runs/1704504073

meanwhile the log is not more available, but as you can see on the job status, cargo fmt went green for all platforms. 
And clippy failed just for one: windows-latest

**Comment by taurr** [comment]
ok, but still crazy and counter intuitive.
