### ISSUE TITLE
--lib provides unexpected results. 

### ISSUE THREAD

**Issue by PointyFluff** [cargo-generate/cargo-generate#665]
**Describe the bug**
--lib give me a `main.rs` rather than a `lib.rs` when used with just a bare-bones Cargo.toml (name="{{project-name}}" is only variable)

** Suspected Cause:  PEBKAC **
Somewhere in the docs I missed how to set up --lib and --bin properly. 

** Steps to reproduce **
create a basic cargo.toml file with just name="{{project-name}}" as the only changed variable, everything else default. 
( note: or add syntactic sugar to handle --bin --lib cases specifically, results are the same ) 
and run `cargo-generate --git --lib https://github.com/torvalds/awesome_rust_library_of_spooky_doom`  ( <- but with a real project )

**Comment by sassman** [comment]
I'm not sure if I follow. `cargo-generate` does not mimic `cargo init`.

The [docs](https://cargo-generate.github.io/cargo-generate/templates/builtin_placeholders.html) says:

> {{crate_type}}
>
> this is supplied by either passing the --bin or --lib flag to the command line, contains either bin or lib, --bin is the default

That means the template author must explicitly consider the lib and the bin case. If the author does not handle the 2 cases, then `cargo-generate` cannot do anything about it.

**Comment by PointyFluff** [comment]
guess I'm confused then, why does it give me a generic main.rs at all?

**Comment by sassman** [comment]
It gives you whatever the template author provides you. 

e.g. If a template author at: `https://github.com/acme/superlib.git` would provide you with a library-only template and has no file `main.rs` in there, then you would not get a `main.rs`.

**Comment by taurr** [comment]
> name="{{project-name}}

you could try it out with the [Bevy Template](https://github.com/taurr/bevy-template-rs) instead - it uses these placeholders correctly. So will my [Rust Template](https://github.com/taurr/rust-template-rs), but than one needs a little TLC and wont be updated until the weekend

**Comment by taurr** [comment]
> ** Suspected Cause: PEBKAC **

LOL... thats an expression I had not heard before -- in Danish this is called "Fejl 40", referring to the error exsisting ~40 cm from the equipment, so in essence the user.

Guess I finally know the english term now 😆
