### ISSUE TITLE
Fails to install with M1 Mac

### ISSUE THREAD

**Issue by mvniekerk** [cargo-generate/cargo-generate#670]
**Describe the bug**
`cargo install` causes a failure on linking with libopenssl_sys

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `cargo install cargo-generate`
2
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/deps/cargo_generate-fe0cd31c4958df17.cargo_generate.27855353-cgu.1.rcgu.o" "-L" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/deps" "-L" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/build/libgit2-sys-ec4cdfbeff1d4c26/out/build" "-L" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/build/libssh2-sys-03d80efb7ef1c804/out/build" "-L" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/build/openssl-sys-8eca36b27fdc1e65/out/openssl-build/install/lib" "-L" "/Users/mike/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/rustcmFLQiW/liblibgit2_sys-88033a7c76185e25.rlib" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/rustcmFLQiW/liblibssh2_sys-cbe752fb494d4327.rlib" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/rustcmFLQiW/libopenssl_sys-5b82242423b038db.rlib" "/Users/mike/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-4014697324d67e93.rlib" "-liconv" "-framework" "Security" "-framework" "CoreFoundation" "-lz" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/mike/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/cargo-install0EgPG8/release/deps/cargo_generate-fe0cd31c4958df17" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: in /var/folders/z6/bb3hl2551njbjfrh0z59z7m40000gn/T/rustcmFLQiW/libopenssl_sys-5b82242423b038db.rlib(ssl_init.o), building for macOS, but linking in object file built for iOS Simulator, for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

**Expected behavior**
To be able to install

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: N/A
 - Build tools: clang
  - Shell: zsh 
 - `rustc --version`:  1.61.0
 - `cargo generate --version`:  N/A

**Additional context**

**Comment by mvniekerk** [comment]
@sassman did you install openssl using brew?

**Comment by nicolaslara** [comment]
doing `cargo install --locked cargo-generate` worked for me. Not sure why, though. If anyone has an explanation it would be great :)

**Comment by sassman** [comment]
@mvniekerk is the issue persisting for you?

**Comment by mvniekerk** [comment]
It seems to be working correctly
