### ISSUE TITLE
Template componentization

### ISSUE THREAD

**Issue by sassman** [cargo-generate/cargo-generate#673]
- As a Template Author
- I want to provide a whole template as components
- So that a user can pick and choose interactively which components he is interested in

## An Example

Given the template repository with the following contents
```plain
.
├── .git
├── .github
│   ├── FUNDING.yml
│   ├── dependabot.yml
│   └── workflows
│       ├── build.yml
│       ├── e2e-test.yml
│       ├── rebase.yml
│       ├── release-binary-assets.yml
│       └── release.yml
├── .gitignore
├── CHANGELOG.md
├── Cargo.toml
├── LICENSE
├── README.md
├── cargo-generate.toml
├── cliff.toml
└── src
    ├── bin
    └── lib
```

As an Author I want to provide as many components that are usable standalone:
- each GitHub Action workflow might be a component on its own
- a `LICENSE` might be a component
- the `src/lib` folder might be one
- the `src/bin` folder might be one
- the base crate (everything left over in the root folder) might be one

When using such a component template repository, the Author should be able to provide in the config file the list of components (name and path) with a user-understandable description that will be used to prompt the user if they want this component or not.

for instance

```sh
Do you want to use the components: 
  - GitHub Build Action     (workflows/build.yml)?   [y/N]: y
  - GitHub Release Action   (workflows/release.yml)? [y/N]: N
  - MIT License             (LICENSE)?               [y/N]: y
...
```

## Discussion

With this feature at hand, a user is able to render specific tiny components into an existing repository. 

One could even bring that forward to have small little features (like rust modules) that a user can then pick when the project grows.

**Comment by sassman** [comment]
@taurr I'm curious what do you think. 

In fact, we have almost everything of that already, it's just not yet accessible to users and configurable by authors in that precise way.

**Comment by taurr** [comment]
@sassman This also sounds a lot like what we have onc we can use the sub-templates with sorting etc.
I also plan to make it so each template can specify it is `--init` - meaning it is designed **not** to be put in its own folder. 

What I don't like about this suggestion is, what about `--silent` mode? How will we select the individual components from CLI or as a favorite?

With my suggestion, you can have a repo full of "component" templates (each sub-template would use `--init` behavior, without the user specifying it). By just expanding the repo, `cargo-generate` will automatically ask what to expand (sorted as the author wants once that issue lands). The author would just have to "componize" the repo (I was already planning on just such a template).

So all in all, I see this suggestion solved very soon - just by solving whats already in the pipe 😄

**Comment by taurr** [comment]
I suppose it can be done if we merge #679

@sassman could you provide a few GH actions that could be used in an example? I will then create a small example template under `example-templates` that basically does this, using sub-templates and implicit `--init` behavior

**Comment by taurr** [comment]
With the new features, we already have everything in place and this is already possible.

What is missing is a chapter in the book, and an example.

**Comment by taurr** [comment]
@sassman, if you use the newest dev version of `cargo-generate`, please try my template:
```shell
cargo generate --git https://github.com/taurr/rust-template-rs --branch taurr/issue_#4
```

I've split the template in parts, and I suspect the outcome, with our current features, is what you are requesting?

**Comment by taurr** [comment]
@sassman I believe you can now do all that's needed - at least I utilize the combination of subtemplates and the init behaviour in both my [rust](https://github.com/taurr/rust-template-rs) and [bevy](https://github.com/taurr/bevy-template-rs) templates.

Can you think of anything missing, or can we close this one?

**Comment by taurr** [comment]
@sassman can this be closed?
