### ISSUE TITLE
Error parsing the `--git` flag with the short `user/repository` template URL

### ISSUE THREAD

**Issue by aelesbao** [cargo-generate/cargo-generate#674]
## Describe the bug

When using the `--git` flag, the plugin fails to parse the short `user/repository` template URL, throwing an `unsupported URL protocol; class=Net (12)` error.

**Make sure**

- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

## To Reproduce

1. `cargo generate --git CosmWasm/cw-template --name starter-contract`
1. See error:
```
Error: Please check if the Git user / repository exists.

Caused by:
    unsupported URL protocol; class=Net (12)
```

## Screenshots

**Working example**

<img width="1077" alt="Screen Shot 2022-06-29 at 12 35 34" src="https://user-images.githubusercontent.com/466801/176416654-95c4bb39-6875-44d0-86b8-b7ed7bf777c8.png">

**Failing example**

<img width="618" alt="Screen Shot 2022-06-29 at 12 35 42" src="https://user-images.githubusercontent.com/466801/176416677-fb9ae0f7-c963-4a68-b255-889275f43476.png">

## Desktop (please complete the following information):
 - OS: MacOS
 - Version: 12.4
 - Build tools: gcc
 - Shell: zsh
 - `rustc --version`: `rustc 1.61.0 (fe5b13d68 2022-05-18)`
 - `cargo generate --version`: `cargo-generate 0.15.2`

**Comment by taurr** [comment]
Drop the `.git` at the end and it works 😄 

Try:
```shell
cargo-generate --git CosWasm/cw-template --name starter-contract
```

**Comment by taurr** [comment]
Works without issues on Linux (Manjaro, uptated today!)

But... it does **not** work on windows 10 either!

It may somehow be connected to the fact that the template in question is no longer under the `CosmWasm` username, but the `InterWasm`.
Specifying the full URL works.

**Comment by spiwocoal** [comment]
Same problem here on Manjaro (updated today), both with and without the `--git` flag.
```
$ uname -a
Linux linux-desktop 5.19.17-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Nov 6 00:08:27 UTC 2022 x86_64 GNU/Linux

$ rustc -V
rustc 1.65.0 (897e37553 2022-11-02)

$ cargo -V
cargo 1.65.0 (4bc8f24d3 2022-10-20)

$ cargo-generate -V
cargo generate 0.17.3

$ echo $SHELL
/usr/bin/fish
```

Examples:
```
$ cargo generate --git rust-github/template
Error: Please check if the Git user / repository exists.

Caused by:
    unsupported URL protocol; class=Net (12)

$ cargo generate rust-github/template
Error: Please check if the Git user / repository exists.

Caused by:
    unsupported URL protocol; class=Net (12)

$ cargo generate gh:rust-github/template
# [Works as expected]
```

**Comment by sassman** [comment]
That's definitely a regression.

Just to be sure, your .gitconfig does not contain any url http to ssh rewrite sort of config?

**Comment by spiwocoal** [comment]
@sassman Nope, nothing like that on my .gitconfig...

**Comment by sassman** [comment]
a bit time back we changed the behavior or the `--git` argument. It only accepts proper urls anymore. 

So you have 3 options of using it now:
1. `cargo generate rust-github/template`
2. `cargo generate gh:rust-github/template`
3. `cargo generate --git <full-qualified-url-to-the-repo>`

**Comment by spiwocoal** [comment]
Yes, the last two options work for me, but the first one still isn't working.
As I pointed in my first comment, I get the exact same error both with and without the `--git` flag, even though it is supposed to fail only when I use the flag.
This seems to be the same problem as in issue #752.
