### ISSUE TITLE
Cannot input project name after cargo generate

### ISSUE THREAD

**Issue by jerzh** [cargo-generate/cargo-generate#675]
I just installed Rust today and don't have any packages installed except for `wasm-pack`, as I'm following the rust-wasm tutorial. Upon running `cargo generate --git https://github.com/rustwasm/wasm-pack-template`, I run into a strange issue (see .gif below) where I am unable to enter the project name to proceed with the project generation. I am completely new to Rust, so I have no idea what might be causing the issue (maybe a configuration on my bash terminal?)

- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

1. Run `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
2. This results in the following behavior:

![cargo-generate](https://user-images.githubusercontent.com/33165824/177027013-871742de-50f6-4549-ba7c-7655ec6d51dc.gif)

Expected behavior: Cargo project initializes from the given Git repo as expected.

System details:
 - OS: MacOS (Mac M1)
 - Shell: bash
 - `rustc --version`: 1.62.0
 - `cargo generate --version`: 0.15.2

**Comment by taurr** [comment]
Yeah, no idea what the issue is, and next to impossible to reproduce,but I do have a potential way forward - specify the name on the command line.

```shell
cargo generate --git https://github.com/rustwasm/wasm-pack-template --name MY-PROJECT-NAME
```

**Comment by jerzh** [comment]
Thanks! I ended up just git cloning the repo and manually editing it, but I'll try this in the future. Hopefully someone else experiences a similar issue so there'll be some idea of why this happens -- it's a strange bug and I've never seen anything like it, even with my current terminal setup. As far as I know I've also updated bash to the latest version.

**Comment by taurr** [comment]
On hold for now as it is very hard to replicate and may be solved indirectly (maybe its in the `dialoger` dependency).

Holding on to it just to see if anybody else experiences this bug.
