### ISSUE TITLE
Nested Conditionals

### ISSUE THREAD

**Issue by thor314** [cargo-generate/cargo-generate#698]
I'd like to have a couple nested conditionals in my template:

crate is lib?
- true -> ask: crate is workspace?
  - t -> ok cool
  - f -> ask: minimal template?
    - t
    - f
- false -> no worries, keep on chugging

I've tried a couple things, this seemed like the best shot:
```
[conditional.'crate_type == "lib"'.placeholders]
workspace = { type = "bool", prompt = "Workspace? Default no.", default = false } 

[conditional.'workspace == false'.placeholders]
minimal = { type = "bool", prompt = "Minimal? Excludes licensing, contributing, CI. Good when creating new crates inside a workspace.",  default = false }
```
The next shot is probably to use Rhai, but I wanted to ask if there was an easy way I hadn't considered before doing so.

**Comment by taurr** [comment]
you are on the right track - unfortunately the current version doesn't support this - I've already fixed it and it will be part of the next release. When that'll be is a little harder, as Sassman is quite busy atm., but it's coming.
