### ISSUE TITLE
Failing to install via cargo install

### ISSUE THREAD

**Issue by 4kmartin** [cargo-generate/cargo-generate#703]
system: HP probook    
OS: Windows 10 21h2

Error:
Compiling cargo-generate v0.15.2
error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:165:32
    |
165 |     pub const fn git(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:169:35
    |
169 |     pub const fn branch(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:173:33
    |
173 |     pub const fn path(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:177:37
    |
177 |     pub const fn favorite(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:181:38
    |
181 |     pub const fn auto_path(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

error[E0658]: `impl Trait` is not allowed in constant functions
   --> C:\Users\anthany.martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-generate-0.15.2\src\args.rs:185:38
    |
185 |     pub const fn subfolder(&self) -> Option<&(impl AsRef<str> + '_)> {
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #77463 <https://github.com/rust-lang/rust/issues/77463> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `cargo-generate` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by sassman** [comment]
Please update your rustc version

**Comment by 4kmartin** [comment]
ah i am an idiot!
