### ISSUE TITLE
Release Binary Assets failed for release `0.16.0`

### ISSUE THREAD

**Issue by SergioGasquez** [cargo-generate/cargo-generate#708]
[CI for releasing assets for `0.16.0` failed](https://github.com/cargo-generate/cargo-generate/runs/7499419924?check_suite_focus=true) with:
```bash
Error: The process '/home/runner/.cargo/bin/cross' failed with exit code 2
```

**Comment by SergioGasquez** [comment]
I am not sure if this is something you can fix on your end, or if it's related to `cross` but in any case, we could comment the smoke test to rerun the actions and have the binaries available for the failing architectures.

**Comment by sassman** [comment]
Looks a bit like `cross` accept arguments now somehow different than before. Not sure but a manual trigger would be a good idea as well.

**Comment by SergioGasquez** [comment]
> Looks a bit like `cross` accept arguments now somehow different than before. Not sure but a manual trigger would be a good idea as well.

Running the same commands on my local machine does not throw the error that we are seeing in the CI:
```
❯ cross build --features vendored-openssl --release --target=x86_64-unknown-linux-musl
    Finished release [optimized] target(s) in 0.14s

❯ cross run --features vendored-openssl --release --target=x86_64-unknown-linux-musl -- --version
    Finished release [optimized] target(s) in 0.11s
     Running `/qemu-runner x86_64 /target/x86_64-unknown-linux-musl/release/cargo-generate`
cargo generate 0.16.0
cargo, make me a project

USAGE:
    cargo <SUBCOMMAND>

OPTIONS:
    -h, --help       Print help information
    -V, --version    Print version information

SUBCOMMANDS:
    generate    cargo, make me a project [aliases: gen]
    help        Print this message or the help of the given subcommand(s)
```

**Comment by jessebraham** [comment]
Why is `cross` being used at all? AFAIK all of these failing targets can be built on `ubuntu-latest` without it.

**Comment by SergioGasquez** [comment]
Hello @sassman, do you have any updates regarding this issue? Would you accept a PR commenting the `smoke test` step just to get the release binaries generated? Our CI uses the binaries and it's currently failing because of this issue.

**Comment by SergioGasquez** [comment]
Hello @sassman! Since #721 got merged, could we rerun the `Release Binary Assets` action and close this issue?

**Comment by SergioGasquez** [comment]
Hello @sassman, sorry for insisting but, do you have any updates regarding this issue?
