### ISSUE TITLE
Install cargo-generate Error!

### ISSUE THREAD

**Issue by BabaiLi** [cargo-generate/cargo-generate#709]
When I use the command `cargo install cargo-generate`, I get an error:

`couldn't read .cargo/registry/src/liquid-core-0.26.0/src/parser/parser/grammar.pest: No such file or directory(os error 2)`

But, I find the file **grammar.pest** in the parent directory, like this:
`.cargo/registry/src/liquid-core-0.26.0/src/parser/grammar.pest`

So, I make a new directory **parser** under **the old parser** and move **grammar.pest** to there.
Although `cargo install cargo-generate` finally works, will this cause problems?

**Comment by taurr** [comment]
good question, but it seems to be a problem with `liquid` and not `cargo-generate`. We have no way of influencing the build of the `liquid` crate due to how Cargo works.

**Comment by sassman** [comment]
@BabaiLi could you please try to install via `cargo install --locked cargo-generate` and see if the issue persists?
