### ISSUE TITLE
Hello! I have a problem with installing cargo-generate

### ISSUE THREAD

**Issue by sor-ca** [cargo-generate/cargo-generate#753]
Update. The problems was with rust version, the updating of Rust helps

Hello! I have a problem with cargo-generate
I run cargo install cargo-generates, and it fails during compiling the last of 227 packeges.
the output is "
error: could not compile `cargo-generate`

Caused by:
  process didn't exit successfully: `rustc --crate-name cargo_generate --edition=2021 C:\Users\Marisha\.cargo\registry\src\github.com-1ecc6299db9ec82
3\cargo-generate-0.16.0\src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,li
nk -C opt-level=3 -C lto -C metadata=f38fba2bd256a671 -C extra-filename=-f38fba2bd256a671 --out-dir C:\Users\Marisha\AppData\Local\Temp\cargo-in16:30
78Ff6m\release\deps -L dependency=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps --extern anyhow=C:\Users\Marisha\AppData\Local
\Temp\cargo-install78Ff6m\release\deps\libanyhow-795ed86479e19b66.rlib --extern cargo_generate=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6
m\release\deps\libcargo_generate-ea6167891ab48eca.rlib --extern clap=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libclap-80b
bea24644d9bd9.rlib --extern console=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libconsole-94d8078d69eb35d6.rlib --extern di
aloguer=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libdialoguer-f7197e67453453f3.rlib --extern dirs=C:\Users\Marisha\AppDat
a\Local\Temp\cargo-install78Ff6m\release\deps\libdirs-4aecaa4dda47d61d.rlib --extern git_config=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff
6m\release\deps\libgit_config-98991cb770c777e3.rlib --extern git2=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libgit2-08e744
45147f7927.rlib --extern heck=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libheck-e444d119149bd628.rlib --extern home=C:\Use
rs\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libhome-efc32a47715b9506.rlib --extern ignore=C:\Users\Marisha\AppData\Local\Temp\carg
o-install78Ff6m\release\deps\libignore-0fad35918b0e61d0.rlib --extern indicatif=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\
libindicatif-be81dce622fccbb2.rlib --extern liquid=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libliquid-b29bb4b2a11774f3.rl
ib --extern liquid_core=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libliquid_core-26fd0c15e802560b.rlib --extern liquid_der
ive=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\liquid_derive-e13f431f67e2b03b.dll --extern liquid_lib=C:\Users\Marisha\AppD
ata\Local\Temp\cargo-install78Ff6m\release\deps\libliquid_lib-fe2598cc4d4cf0f5.rlib --extern names=C:\Users\Marisha\AppData\Local\Temp\cargo-install7
8Ff6m\release\deps\libnames-8e61bf0a863ab4fd.rlib --extern paste=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\paste-aa39227ee
8ecad2e.dll --extern path_absolutize=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libpath_absolutize-62a6de9993872620.rlib --
extern regex=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libregex-2fd0fb7eb4bb2463.rlib --extern remove_dir_all=C:\Users\Mar
isha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libremove_dir_all-94c5ad6790599efc.rlib --extern rhai=C:\Users\Marisha\AppData\Local\Temp\ca
rgo-install78Ff6m\release\deps\librhai-05cb3e5a1030943b.rlib --extern sanitize_filename=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\relea
se\deps\libsanitize_filename-5b8777fbfe1d65cc.rlib --extern semver=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libsemver-ffe
b42d1a325b15e.rlib --extern serde=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libserde-91ef8879a52a2aa4.rlib --extern tempfi
le=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libtempfile-f54dd5bd9a2a88bb.rlib --extern thiserror=C:\Users\Marisha\AppData
\Local\Temp\cargo-install78Ff6m\release\deps\libthiserror-9d613d90ff20c701.rlib --extern toml=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m
\release\deps\libtoml-046f2200d84588dd.rlib --extern walkdir=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\deps\libwalkdir-4fca9f5b
c6259568.rlib --cap-lints allow -L native=C:\Users\Marisha\.cargo\registry\src\github.com-1ecc6299db9ec823\windows_x86_64_msvc-0.36.1\lib -L native=C
:\Users\Marisha\.cargo\registry\src\github.com-1ecc6299db9ec823\windows_x86_64_msvc-0.37.0\lib -L native=C:\Users\Marisha\AppData\Local\Temp\cargo-in
stall78Ff6m\release\build\libgit2-sys-a9e3742d26e10f53\out\build -L native=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\build\libs
sh2-sys-5c1d74767603f321\out\build -L native=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\build\libz-sys-d3d21e4f75ae06d6\out\lib
-L native=C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m\release\build\libz-sys-d3d21e4f75ae06d6\out\lib` (exit code: 0xc0000094, STATUS_INT
EGER_DIVIDE_BY_ZERO)
error: failed to compile `cargo-generate v0.16.0`, intermediate artifacts can be found at `C:\Users\Marisha\AppData\Local\Temp\cargo-install78Ff6m`"
Maybe you may advise me what is the problem?
Windows 7, cargo 1.61.0

**Comment by taurr** [comment]
first, please  try again using newest version of cargo => 1.64.0

`cargo-generate` really, really likes the newest version at all times. Latest changes I did myself on it was due to failing CI as `cargo clippy` failed - turned of a used API was isuing warnings due to the availability of a newer better one!
