### ISSUE TITLE
Despite using --init option, it's still trying to initialize a git repository

### ISSUE THREAD

**Issue by vadorovsky** [cargo-generate/cargo-generate#758]
**Describe the bug**
cargo-generate with `--init` is still trying to initialize a git repository. I wanted to use my already existing Github repository.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `git clone` my already existing repository, enter the directory.
2. `cargo generate --init --git https://github.com/aya-rs/aya-template`
3. Answered all the prompt questions.
4. See error:

```
Error: ⚠️   File already exists: /home/vadorovsky/repos/aya-btf-maps/.git/index
```

**Expected behavior**
Because of using `--init` option, I would expect cargo-generate to not try to create any files in `.git`.

**Screenshots**
![cargo-generate-git-error](https://user-images.githubusercontent.com/34685103/193748983-514b7803-75e9-4c90-a3c3-1eb74cac9b5a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: rolling releasse
 - Build tools: gcc
 - Shell: nushell
 - `rustc --version`: rustc 1.64.0 (a55dd71d5 2022-09-19)
 - `cargo generate --version`: cargo-generate 0.16.0

**Additional context**

**Comment by MalloryA** [comment]
This bug can be tested with the following script:

```
#!/bin/sh
set -xe

cargo build

rm -rf test
mkdir test
git -C test init
sh -c 'cd test && ../target/debug/cargo-generate generate --git https://github.com/rustwasm/wasm-pack-template --name=foo --init'
```
