### ISSUE TITLE
check template pkg metadata for cargo gen version, warn on mismatch

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#76]
to help make it easier for us to proceed without breaking things, i'd like to propose that template authors be required to include a cargo-generate version in their cargo toml, e.g.

```
[package]
name = "{{project-name}}"
version = "0.1.0"
cargo-generate = "0.1.0"
```

if the version doesn't exist in the cargo toml, we should WARN
if the version of cargo-generate on disk is different than the listed version, we should WARN

this should be fully semver feature full, so folks should be able to write something like:
`cargo-generate = "~0.2.0"`

**Comment by killercup** [comment]
- Assumes templates have a Cargo.toml file
- cf. #48 for cargo-generate specific config files

**Comment by ashleygwilliams** [comment]
ah yeah, good call re templates have a Cargo.toml file. i think for the moment we can implement this with a cargo.toml entry and some other thing? not having one just produces a warn, and all current (2) templates that we know of do have a Cargo.toml.

i'm super hesitant re the config files... only because i dont think the UX is that great and i dont think having 100000 substitutions that you can customize is great. making the most out of a small set of substitutions is the ideal product path here, imo. that being said, maybe intro-ing a config file to hold this version number is a reasonable start.

**Comment by durka** [comment]
Are you planning to have `cargo generate` remove this key from Cargo.toml during generation? If not, you get

```
warning: unused manifest key: package.cargo-generate
```

Another option is to use a separate stanza, like [docs.rs does](https://github.com/onur/docs.rs/pull/73), and which other cargo commands ignore:

```toml
[package.metadata.cargo-generate]
version = "0.1.0"
```

**Comment by ashleygwilliams** [comment]
good call @durka - that's how we should do it (if we do it in cargo.toml) :)

**Comment by DD5HT** [comment]
we could also check the age of a template. eg. the last push. 
If it's old and without changes we could warn the user that it might break this solution would work without a .toml or config file, but would require git

**Comment by RotationMatrix** [comment]
Since we have `cargo-generate.toml` now, should we use it or stick with `Cargo.toml`?

Using `cargo-generate.toml` would keep most of the template metadata in one place and, as @killercup pointed out, templates like in #14 wouldn't need a `Cargo.toml`. However the disadvantage would be requiring all templates to have a `cargo-generate.toml`.

**Comment by taurr** [comment]
It doesn't need to be a requirement - we could just support the version check if the template has a `cargo-generate.toml` file, and ignore it if it doesn't.

That way, we get to support version checking _without_ adding any new requirements.
