### ISSUE TITLE
improve error message when passed a git repo that does not exist

### ISSUE THREAD

**Issue by dineshadepu** [cargo-generate/cargo-generate#79]
I am getting an error while creating a cli-wg project `ggrs`.

```
dinesh@Personal /Users/dinesh $  
|  Mac => cargo generate --git https://github.com/rust-clique/cargo-template-cli
🤷  Project Name: grrs
🔧   Creating project called `grrs`...
error: authentication required but no callback set; class=Net (12)
```

**Comment by killercup** [comment]
Yep, that template doesn't exist yet, see 
https://github.com/rust-lang-nursery/cli-wg/issues/53 (and I should really add that TODO to the tutorial!)

We should improve the error message here. I think we can at least add some context (what repo, more info about the [git error type](https://docs.rs/git2/0.7.4/git2/struct.Error.html)), and also print out some common errors (like missing repos or missing permissions).

**Comment by ashleygwilliams** [comment]
go for it @rexto - probably want to build off of what @DD5HT is working on in #85! (would totally accept a PR that's branched off his work)

**Comment by DD5HT** [comment]
I think it would be really good if you write a function like this in 
`git.rs `:
```rust
    pub fn pretty_git_err(err: Error) -> String {
        YOUR IMPLEMENTATION
    }
```

**Comment by taurr** [comment]
Nowadays we actually get

`Error: ⛔   Git Error: unexpected http status code: 404; class=Http (34)`

(404 = Not found, which is correct for a bogus URL)
or

`Error: ⛔   Git Error: unexpected http status code: 400; class=Http (34)`

(400 = Bad Request, which can also be correct as in this case I used the <username>/<repo> syntax, and github found the user, but not the repo)
