### ISSUE TITLE
could not compile cargo-generate

### ISSUE THREAD

**Issue by gamelife1314** [cargo-generate/cargo-generate#798]
run command `cargo install cargo-generate` failed

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/10297148/201522049-467b63be-cabe-400c-a5c5-990f82202c52.png">

environment information:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/10297148/201522118-d4a06ba8-77da-47c6-bb36-806e2492b823.png">

**Comment by sassman** [comment]
can you pls retry on the latest version 0.18.3?
