### ISSUE TITLE
compile to wasm

### ISSUE THREAD

**Issue by ashleygwilliams** [cargo-generate/cargo-generate#80]
i want this to exist for npm init templates- but it doesn't. would be rad if i could compile this to wasm. no idea what the blockers are yet, but i am imagine libgit2 may give us problems... this may be a good reason to resolve #67 by removing libgit2 and shelling out to git (anyone using this tool would already have git installed)

**Comment by fitzgen** [comment]
git command line is also higher level and less footgun-y than libgit2

**Comment by taurr** [comment]
@sassman I don't think this is going to happen considering our dependecies etc.
