### ISSUE TITLE
is it possible to set a variable shared between different files?

### ISSUE THREAD

**Issue by dmitris** [cargo-generate/cargo-generate#847]
Is it possible to set a variable that is not a placeholder? I'd like to set a variable to an array of strings and then use it in conditionals.  Something like:
```
{% assign program_type_with_opts = "xdp, classifier, sock_ops, cgroup_skb, cgroup_sysctl, cgroup_sockopt, uprobe, uretprobe" | split: ", " %}
{% if program_type in program_type_with_opts %}
use clap::Parser;
{% endif %}
```
I saw the `assign` in https://shopify.github.io/liquid/tags/variable/ but was not able to use it in a cargo-generate template.

If this is not possible currently, would you consider an extension allowing this?  It would help to avoid "ugly" workarounds like in https://github.com/aya-rs/aya-template/blob/2ba73f6f2f8b24f15d3d197878191258e7d7d397/%7B%7Bproject-name%7D%7D/src/main.rs#L47-L48 and https://github.com/aya-rs/aya-template/blob/2ba73f6f2f8b24f15d3d197878191258e7d7d397/%7B%7Bproject-name%7D%7D/src/main.rs#L67-L68 😄  Thanks!

Related to https://github.com/aya-rs/aya-template/pull/67 and https://github.com/aya-rs/aya-template/pull/68.

**Comment by dmitris** [comment]
I now figured out how to use the `assign` - therefore modified the subject - and was able to do the following:
```
{% assign program_types_with_opts = "xdp, classifier, sock_ops, cgroup_skb, cgroup_sysctl, cgroup_sockopt, uprobe, uretprobe" | split: ", " %}

{% if program_types_with_opts contains program_type %}
use clap::Parser;
{% endif %}
```

Now I need to figure out how to assign a variable in one file and use it in another in the DRY spirit, to avoid doing it in several places (and risking the later edits getting out of syncs, or having to update the same assignment in multiple places).  Do you know how / where to do it?  `cargo-generate.toml` would be a good place for that - but at least for now, I wasn't able to put the assignment there, would appreciate any hint 😄

**Comment by taurr** [comment]
It is very much possible - just use the variable extension as described in [the book](https://cargo-generate.github.io/cargo-generate/templates/scripting.rhai-extensions.html).

You cannot use the Rhai assign keyword for this, as Rhai sees each file as its own, and not as a project - thus **there's NO carryover between files. Nor is there a specific order!!!**

I would probably create a small file with the shared functionality, exclude it from the actual templatefiles (using cargo-generate.toml), and include this shared file where its needed using the Rhai include keyword.

**Comment by dmitris** [comment]
thanks @taurr!  Still not fully clear - the Rhai script, does it need to be declared in a hook, like in the `pre` hook in https://cargo-generate.github.io/cargo-generate/templates/scripting.mini-example.html?  Or is there a tag that allows to "inline" a Rhai script snippet in the template file itself, like `Cargo.toml`?  Something like `{% rhai include_file ../../common.rhai %}`?  Do you know of any examples that use `cargo-generate` and have such Rhai scripts?  Many thanks! 😄

**Comment by taurr** [comment]
There is no special `liquid` tags for executing `rhai` scripts (though the functionality *could* be implemented as a filter - which I see could be useful).

For scripts to be executed, they currently must be used in some hook. However, `rhai` itself allows to import other files as part of the executing script - see [Rhai - import modules](https://rhai.rs/book/language/modules/import.html).

When having files used as modules for the `rhai` script, they probably shouldn't be expanded and included in the output of `cargo-generate`, thus the need to `ignore` them in the `cargo-generate.toml` file.

**Comment by dmitris** [comment]
Yay, was able to figure out how to use a rhai script in the `pre` hook to set the variable I need!

@taurr one more question, if you don't mind - I'm trying to grasp the difference between `{%` / `%`, `{%-` and `-%}` in the conditional tags.  It must have to do with deleting or leaving the newspace after the line - is it documented somewhere? and if so, where? (Sorry if I'm missing the obvious! 😄 ) Thanks!

**Comment by dmitris** [comment]
from playing with it, my "empirical" guess is:
* `{%` - adds a newline after the conditional (?)
* `{%-` - doesn't add a newline, preserves the leading space on the next line
* ` -%}` - "eats up" all the leading whitespace on the following line

Following these guesses, I used those modifiers in https://github.com/aya-rs/aya-template/pull/68/files to make the generated files pass `cargo +nightly fmt --check`.

**Comment by dmitris** [comment]
figured out it must be jinja2 template syntax - one reference is here: https://ttl255.com/jinja2-tutorial-part-3-whitespace-control/

**Comment by taurr** [comment]
It's all in the Rhai documentation. Cargo generate only adds a few functions which are mentioned in the docs.

For template stuff, think Liquid.
Specific for the whitespace control: https://shopify.github.io/liquid/basics/whitespace/

For scripts, think Rhai, sprinkled with a few cargo-generate functions.

**Comment by dmitris** [comment]
thanks for your help and the links @taurr!
