### ISSUE TITLE
Release action failed for release v0.17.5

### ISSUE THREAD

**Issue by SergioGasquez** [cargo-generate/cargo-generate#852]
**Describe the bug**
[Release action failed for `v0.17.5`](https://github.com/cargo-generate/cargo-generate/actions/runs/3930499614) hence, the binary artifacts are not updated.

I think the issue was maybe introduced in [`d77844c`](https://github.com/cargo-generate/cargo-generate/commit/d77844ccb5c0431e40dfa0d03fe3c9856805db0f) as the `Install cargo-deb and create a deb` is only executed on `ubuntu-latest` but `Upload the deb to release files`, which consumes the output of the previous step, is executed with all the OSs

**Comment by sassman** [comment]
should be solved by #853
