### ISSUE TITLE
Feat: New `Liquid` filter for running a `Rhai` script

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#855]
Based on a discussion in #847, the idea came up to have a `Liquid` filter to allow executing `Rhai` scripts and include the output in the template.

I'm currently thinking on a syntax like 

```liquid
Example execution of a Rhai script: {{script_file|rhai}}
```

Caveat: at `Liquid` filters only takes 1 parameter, it's rather hard to pass anything to the `Rhai` scripts without misusing the syntax in some way - which is why I am not proposing parameters for the `Rhai` script. Ideas or alternatives more than welcome.

**Comment by dmitris** [comment]
nit on Feat: `s/Fea:/Feat: ` in the Subject 😄
