### ISSUE TITLE
'cargo generate' doesn't indicate the file name on a bad cargo-generate.toml file

### ISSUE THREAD

**Issue by dmitris** [cargo-generate/cargo-generate#857]
```
$ cargo generate -v -p /tmp/tmpl01 -o
Error: newline in string found at line 3 column 50
```

The cargo-generate.toml  file was badly formatted - had a missing closing quote:
```
[template]
cargo_generate_version = ">=0.10.0"
ignore = [".github", "test.sh", "pre-script.rhai]
```

but I think it would be nice if the output would mention the filename and path of the faulty file, for example:
```
Error: newline in string found at /tmp/tmpl01/cargo-generate.toml line 3 column 50



**Desktop (please complete the following information):**
 - OS: MacOs
 - Version: 12.6.2
 - Shell: bash
 - `rustc --version`: rustc 1.66.1 (90743e729 2023-01-10)
 - `cargo generate --version`: cargo generate-generate 0.17.6

**Comment by taurr** [comment]
just ran against newest release `0.17.6`:

```shell
❯ cargo generate cli
💡   Using application config: /home/johnny/.cargo/cargo-generate.toml
Error: newline in string found at line 3 column 10
```

Works perfectly - even states the name of the failing config file.

@dmitris : I think you've been using an old version... could you try again?

**Comment by dmitris** [comment]
I have the latest version but I still see the issue.  I use the template from (a local checkout of) https://github.com/aya-rs/aya-template with one quote removed in a JSON value https://github.com/aya-rs/aya-template/blob/main/cargo-generate.toml#L9, diff being:
```
diff --git a/cargo-generate.toml b/cargo-generate.toml
index a977b33..9a0f748 100644
--- a/cargo-generate.toml
+++ b/cargo-generate.toml
@@ -6,7 +6,7 @@ ignore = [".github", "test.sh"]
 type = "string"
 prompt = "Which type of eBPF program?"
 choices = [
-    "cgroup_skb",
+    "cgroup_skb,
     "cgroup_sockopt",
     "cgroup_sysctl",
     "classifier",
```

Then I run the cargo generate command:
```
$ cargo generate --name mytest -d program_type=xdp --path=/Users/dmitris/gh/aya-rs/aya-template
program_type => 'xdp'
Error: newline in string found at line 9 column 17
C02ZM0NNLVDV:tmp dmitris$ cargo install cargo-generate
    Updating crates.io index
     Ignored package `cargo-generate v0.17.6` is already installed, use --force to override
```

no filename is indicated - I would expect something like "bad TOML syntax in /Users/dmitris/gh/aya-rs/aya-template/cargo-generate.toml line 9 (it does say "line 9 column 17" which is great, just need to add the filename).

**Comment by stappersg** [comment]
> I have the latest version but I still see the issue.

Meanwhile it is August 2023.


> ```
> C02ZM0NNLVDV:tmp dmitris$ cargo install cargo-generate
>     Updating crates.io index
>      Ignored package `cargo-generate v0.17.6` is already installed, use --force to override
> ```

@dmitris  please  execute

```text
cargo install --force cargo-generate
cargo generate --version
```

and update this issue.  (Closing this issue would also be appreciated.)

**Comment by dmitris** [comment]
I have `cargo generate-generate 0.18.3` and the error now is:
```
program_type => 'xdp'
Error: TOML parse error at line 9, column 17
  |
9 |     "cgroup_skb,
  |                 ^
invalid basic string
```
I think this is fine, thanks! Closing the issue.
