### ISSUE TITLE
malformed URL ''; class=Net (12)

### ISSUE THREAD

**Issue by jmmaa** [cargo-generate/cargo-generate#858]
**Describe the bug**
Doesn't generate from inputs with `--git` flag

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
1. `cargo generate --git https://github.com/Rahix/avr-hal-template.git`
2. output it generated..
```
PS D:\github> cargo generate --git https://github.com/Rahix/avr-hal-template    
Error: Please check if the Git user / repository exists.

Caused by:
    malformed URL ''; class=Net (12)
```

**Expected behavior**
It should be able to normally prompt the project details

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1909
 - Build tools: msvc
 - Shell: powerShell
 - `rustc --version`: 1.66.0
 - `cargo generate --version`: 0.17.4

**Additional context**
The avr-hal-template author suggests to raise the [issue](https://github.com/Rahix/avr-hal-template/issues/16) here.

**Comment by sassman** [comment]
Do you have any url replace magic in your gitconfig that you can share?

**Comment by jmmaa** [comment]
> Do you have any url replace magic in your gitconfig that you can share?
> 
> something like this might cause it, in combination with passphrase protected ssh-keys that are not registered at the ssh-agent.
> 
> ```
> [url "git@github.com:"]
>     insteadOf = https://github.com/
> ```

I haven't really set up any of git config similar to above snippet, but I figure that it maybe because I havent installed openssl. Its working now thanks.
