### ISSUE TITLE
dedicated section for cargo-generate specific liquid filters in the docs

### ISSUE THREAD

**Issue by sassman** [cargo-generate/cargo-generate#881]
adding documentation for feature #855

**Comment by taurr** [comment]
Already in the book: https://cargo-generate.github.io/cargo-generate/templates/index.html#additional-liquid-filters

**Comment by taurr** [comment]
but maybe we should move the text on the liquid filters to its own chapter under templates - like we have one for the Rhai extensions?

**Comment by sassman** [comment]
I totally missed it.

> but maybe we should move the text on the liquid filters to its own chapter under templates - like we have one for the Rhai extensions?

I guess that would improve the docs structure, since for placeholders we have `[5.1. Builtin Placeholders](https://cargo-generate.github.io/cargo-generate/templates/builtin_placeholders.html)` so having a section for filters makes total sense. 

Very good idea.
