### ISSUE TITLE
Cannot install 0.18.0 on windows

### ISSUE THREAD

**Issue by iTitus** [cargo-generate/cargo-generate#883]
**Describe the bug**
`cargo-generate` does not build/install, caused by openssl.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [x] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo install cargo-generate`
1. See error

**Expected behavior**
`cargo-generate` should install.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Build tools: msvc
 - Shell: N/A
 - `rustc --version`: rustc 1.67.1 (d5a82bbd2 2023-02-07)
 - `cargo generate --version`: trying to install 0.18.0

**Additional context**

```
cargo install cargo-generate 
    Updating crates.io index
  Installing cargo-generate v0.18.0
   Compiling proc-macro2 v1.0.51 
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23       
   Compiling autocfg v1.1.0      
   Compiling syn v1.0.107        
   Compiling cfg-if v1.0.0       
   Compiling once_cell v1.17.1   
   Compiling memchr v2.5.0       
   Compiling thiserror v1.0.38   
   Compiling winapi v0.3.9
   Compiling libc v0.2.139
   Compiling jobserver v0.1.25
   Compiling windows_x86_64_msvc v0.42.1
   Compiling pkg-config v0.3.26
   Compiling version_check v0.9.4
   Compiling vcpkg v0.2.15
   Compiling regex-automata v0.1.10
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling serde_derive v1.0.152
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.152
   Compiling cc v1.0.79
   Compiling time-core v0.1.0
   Compiling time-macros v0.2.7
   Compiling itoa v1.0.5
   Compiling bitflags v1.3.2
   Compiling num-traits v0.2.15
   Compiling smallvec v1.10.0
   Compiling crossbeam-utils v0.8.14
   Compiling hashbrown v0.12.3
   Compiling lock_api v0.4.9
   Compiling memoffset v0.7.1
   Compiling regex-syntax v0.6.28
   Compiling ucd-trie v0.1.5
   Compiling crunchy v0.2.2
   Compiling parking_lot_core v0.9.7
   Compiling windows-targets v0.42.1
   Compiling crossbeam-epoch v0.9.13
   Compiling windows-sys v0.45.0
   Compiling getrandom v0.2.8
   Compiling log v0.4.17
   Compiling tiny-keccak v2.0.2
   Compiling signal-hook v0.3.15
   Compiling either v1.8.1
   Compiling fastrand v1.9.0
   Compiling static_assertions v1.1.0
   Compiling bstr v1.3.0
   Compiling aho-corasick v0.7.20
   Compiling openssl-src v111.25.0+1.1.1t
   Compiling signal-hook-registry v1.4.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling percent-encoding v2.2.0
   Compiling tinyvec_macros v0.1.1
   Compiling lazy_static v1.4.0
   Compiling quick-error v2.0.1
   Compiling minimal-lexical v0.2.1
   Compiling hex v0.4.3
   Compiling tinyvec v1.6.0
   Compiling proc-quote-impl v0.3.2
   Compiling nom v7.1.3
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.2
   Compiling sha1_smol v1.0.0
   Compiling rayon-core v1.10.2
   Compiling const-random-macro v0.1.15
   Compiling libz-sys v1.1.8
   Compiling libssh2-sys v0.2.23
   Compiling btoi v0.4.3
   Compiling openssl-sys v0.9.80
   Compiling libgit2-sys v0.14.2+1.5.1
   Compiling crossbeam-deque v0.8.2
   Compiling crossbeam-channel v0.5.6
   Compiling itertools v0.10.5
   Compiling rand_core v0.6.4
   Compiling windows-sys v0.42.0
   Compiling ahash v0.8.3
   Compiling smartstring v1.0.1
   Compiling num_cpus v1.15.0
   Compiling portable-atomic v0.3.19
   Compiling encode_unicode v0.3.6
   Compiling time v0.3.19
   Compiling regex v1.7.1
   Compiling unicode-normalization v0.1.22
   Compiling unicode-width v0.1.10
   Compiling ppv-lite86 v0.2.17
   Compiling doc-comment v0.3.3
   Compiling anymap2 v0.13.0
   Compiling unicode-bidi v0.3.10
   Compiling dashmap v5.4.0
   Compiling rand_chacha v0.3.1
   Compiling const-random v0.1.15
   Compiling form_urlencoded v1.1.0
   Compiling idna v0.3.0
   Compiling nom8 v0.2.0
   Compiling windows v0.43.0
   Compiling unicode-segmentation v1.10.1
   Compiling foreign-types-shared v0.1.1
   Compiling anyhow v1.0.69
   Compiling openssl v0.10.45
   Compiling heck v0.4.1
   Compiling fnv v1.0.7
   Compiling paste v1.0.11

Caused by:
  process didn't exit successfully: `C:\Users\iTitus\AppData\Local\Temp\cargo-installdCSqZ8\release\build\openssl-sys-b10c3ade16499e19\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\iTitus\\AppData\\Local\\Temp\\cargo-installdCSqZ8\\release\\build\\openssl-sys-4a38ccc4d84b043b\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shar
ed" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\iTitus\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.0+1.1.1t\src\lib.r
s:497:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.18.0`, intermediate artifacts can be found at `C:\Users\iTitus\AppData\Local\Temp\cargo-installdCSqZ8`
```

**Comment by Indrazar** [comment]
Build fails on Windows 11 even with the `OPENSSL_DIR` environment variable set.

**Comment by iTitus** [comment]
I don't think installing OpenSSL or Perl should be required to build this tool.

**Comment by FMFigueroa** [comment]
I have the same problem, yesterday they fixed another dependency error, was gitoxide which caused inference issues due to mis-use of as_ref()., but now it's openssl-sys who is causing el bug.

**Comment by iTitus** [comment]
@FMFigueroa created the corresponding issue over at sfackler/rust-openssl#1826 .

**Comment by FMFigueroa** [comment]
@iTitus  were you able to install cargo-generate ?.. if possible could you share the fix, thanks..!

**Comment by iTitus** [comment]
> @iTitus  were you able to install cargo-generate ?.. if possible could you share the fix, thanks..!
> 
> 
> 
> 

No I did not. I don't have Perl or OpenSSL installed/setup correctly.

**Comment by FMFigueroa** [comment]
I was able to do it by installing https://strawberryperl.com/

**Comment by Araxeus** [comment]
got errors about perl missing - installed [strawberryperl.com](https://strawberryperl.com/)
got errors about make missing - installed [gnuwin32-make](https://gnuwin32.sourceforge.net/packages/make.htm)

now im getting some error I can't even understand
```
  running "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\nmake.exe" "build_libs"
        "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\crypto\bn_conf.h.in" > include\crypto\bn_conf.h
        "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\crypto\dso_conf.h.in" > include\crypto\dso_conf.h
        "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\openssl\opensslconf.h.in" > include\openssl\opensslconf.h
        C:\Program Files (x86)\GnuWin32\bin\make.exe /                   depend && C:\Program Files (x86)\GnuWin32\bin\make.exe /                   _build_libs

  --- stderr

  Microsoft (R) Program Maintenance Utility Version 14.35.32215.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

  'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
  NMAKE : fatal error U1077: 'C:\Program Files (x86)\GnuWin32\bin\make.exe /                   depend && C:\Program Files (x86)\GnuWin32\bin\make.exe /                   _build_libs' : return code '0x1'
  Stop.
  thread 'main' panicked at '


  Error building OpenSSL:
      Command: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\nmake.exe" "build_libs"
      Exit status: exit code: 2


      ', C:\Users\Araxeus\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.0+1.1.1t\src\lib.rs:499:13
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
     2: openssl_src::Build::build
     3: openssl_src::Build::build
     4: build_script_main::find_vendored::get_openssl
     5: build_script_main::env::{{closure}}
     6: build_script_main::find_openssl::{{closure}}
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.18.0`, intermediate artifacts can be found at `C:\Users\Araxeus\AppData\Local\Temp\cargo-installyHsgvk`
```

**Comment by FMFigueroa** [comment]
> got errors about perl missing - installed [strawberryperl.com](https://strawberryperl.com/) got errors about make missing - installed [gnuwin32-make](https://gnuwin32.sourceforge.net/packages/make.htm)
> 
> now im getting some error I can't even understand
> 
> ```
>   running "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\nmake.exe" "build_libs"
>         "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\crypto\bn_conf.h.in" > include\crypto\bn_conf.h
>         "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\crypto\dso_conf.h.in" > include\crypto\dso_conf.h
>         "C:\Strawberry\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\openssl\opensslconf.h.in" > include\openssl\opensslconf.h
>         C:\Program Files (x86)\GnuWin32\bin\make.exe /                   depend && C:\Program Files (x86)\GnuWin32\bin\make.exe /                   _build_libs
> 
>   --- stderr
> 
>   Microsoft (R) Program Maintenance Utility Version 14.35.32215.0
>   Copyright (C) Microsoft Corporation.  All rights reserved.
> 
>   'C:\Program' is not recognized as an internal or external command,
>   operable program or batch file.
>   NMAKE : fatal error U1077: 'C:\Program Files (x86)\GnuWin32\bin\make.exe /                   depend && C:\Program Files (x86)\GnuWin32\bin\make.exe /                   _build_libs' : return code '0x1'
>   Stop.
>   thread 'main' panicked at '
> 
> 
>   Error building OpenSSL:
>       Command: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\nmake.exe" "build_libs"
>       Exit status: exit code: 2
> 
> 
>       ', C:\Users\Araxeus\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.0+1.1.1t\src\lib.rs:499:13
>   stack backtrace:
>      0: std::panicking::begin_panic_handler
>                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
>      1: core::panicking::panic_fmt
>                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
>      2: openssl_src::Build::build
>      3: openssl_src::Build::build
>      4: build_script_main::find_vendored::get_openssl
>      5: build_script_main::env::{{closure}}
>      6: build_script_main::find_openssl::{{closure}}
>      7: core::ops::function::FnOnce::call_once
>   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-generate v0.18.0`, intermediate artifacts can be found at `C:\Users\Araxeus\AppData\Local\Temp\cargo-installyHsgvk`
> ```
you have a compiler conflict, check the environment variables and disable GnuWin32, so that Perl is the only GCC compiler

**Comment by Araxeus** [comment]
Thank you. I had an environment variable called `make` pointing to `C:\Program Files (x86)\GnuWin32\bin\make.exe`
Deleting it fixed the problem.

**Comment by sassman** [comment]
for clarification, `cargo-generate` uses the [openssl crate](https://docs.rs/openssl/latest/openssl/#vendored) with the feature `vendored`. Quoting their docs:

> If the vendored Cargo feature is enabled, the openssl-src crate will be used to compile and statically link to a copy of OpenSSL. The build process requires a C compiler, perl (and perl-core), and make. The OpenSSL version will generally track the newest OpenSSL release, and changes to the version are not considered breaking changes.

So that means, a compiler (gcc), perl, perl-core and make are required for openssl to build.

If you explicitly do not want openssl to be build, then you can try to install cargo generate without the `vendored-openssl` feature enabled, like below:

```sh
cargo install cargo-generate --features vendored-libgit2 --no-default-features
```

**Comment by sassman** [comment]
I think it's better to go back to opt in to `vendored-openssl` by default, since this seemed to have been working in other versions prior to `v0.18`

The PR #887 will address this and cargo-generate `v0.18.1` will carry out the fix.

**Comment by iTitus** [comment]
works again, thank you!
