### ISSUE TITLE
Replace println! with logging for API users of cargo-generate

### ISSUE THREAD

**Issue by mothran** [cargo-generate/cargo-generate#899]
**Describe the bug**
Currently cargo-generate prints message to the user via println / eprintln. This works well when using it as a CLI tool but if a user wants to extend the tool via the API from: https://docs.rs/cargo-generate/0.18.1/cargo_generate/ or wrap it. It would be nice to be able to redirect or silence the logging.

**Expected behavior**
Via the cargo-generate cli entrypoint I would expect registering a env_logger or tracing_subscriber that then wrote to stdout, but when calling https://docs.rs/cargo-generate/0.18.1/cargo_generate/fn.generate.html or other methods exposed by the API, allow the caller to define the logging behavior.

I would be happy to provide a PR if the team has a preferred logging engine (ex: `log` vs `tracing`)

Thanks!

**Comment by sassman** [comment]
Sounds reasonable, `log` and `env_logger` should be sufficient for this use case.
