### ISSUE TITLE
Build failure due to gix-config after cargo-update

### ISSUE THREAD

**Issue by mothran** [cargo-generate/cargo-generate#931]
**Describe the bug**
After running `cargo update` on the cargo-generate library (or in project that depends on cargo-generate without a .lock file) the build fails due to changes in the `gix-config` crate.

Build error:

```
error[E0425]: cannot find value `env_var` in crate `gix_path`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gix-config-0.20.1/src/file/init/comfort.rs:31:54
   |
31 |                     .storage_location(&mut gix_path::env_var)
   |                                                      ^^^^^^^ not found in `gix_path`

....
```

**To Reproduce**
1. git fetch'd cargo-generate `main` (tested on 1eea043ebcc9d3e30a1a0c391afff89ca38a1b67)
2. `cargo update`
3. `cargo check`

**Expected behavior**

build to succeed

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: `6.2.11-arch1-1`
 - Build tools: clang
 - Shell: zsh
 - `rustc --version`: rustc 1.66.1 (90743e729 2023-01-10)

**Additional context**

Seems to be fixed by bumping the gix-config dep:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 4611262..b7091b3 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -27,7 +27,7 @@ home = "~0.5"
 sanitize-filename = "~0.4"
 rhai = "~1.13"
 path-absolutize = "~3.0"
-gix-config = "0.20"
+gix-config = "0.21"
 paste = "~1.0"
 names = { version = "~0.14", default-features = false }
 log = "~0.4"
```

**Comment by ltfschoen** [comment]
I get this same error after updating Rust with `rustup update` when I get up to the step of running `cargo install cargo-generate` when following these setup instructions to learn Rust and Wasm https://rustwasm.github.io/docs/book/game-of-life/setup.html

I'm using toolchain `stable-2023-03-28-x86_64-apple-darwin` on macOS with `rustc 1.68.2 (9eb3afe9e 2023-03-27)`

**Comment by mothran** [comment]
Closing because gix-config bumped to 0.22 and fixed the issues upstream: https://github.com/Byron/gitoxide/commit/94564df0b5edcb41f1088c6db04add851c66b2af
