### ISSUE TITLE
--define fails if its value is empty

### ISSUE THREAD

**Issue by mamekoro** [cargo-generate/cargo-generate#947]
**Describe the bug**
When I specify command-line argument `--define PLACEHOLDER=`, `cargo generate` returns an error. I expected `PLACEHOLDER` to have an empty value.

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [x] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. Here is a bash script to reproduce:
```bash
mkdir -p /tmp/template
cd /tmp/template

cat <<'_EOF_' >cargo-generate.toml
[placeholders.command]
type = "string"
prompt = "command name"
_EOF_

cargo generate \
    --verbose \
    --bin \
    --path /tmp/template \
    --destination /tmp/dest \
    --define command=
```
2. output it generated..
```text
Error: ⛔   Failed to parse value: command=
```

**Expected behavior**
The placeholder `command` should have an empty value.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 22.04 (Linux kernel 5.19.0-42-generic)
 - Build tools: N/A
 - Shell: bash
 - `rustc --version`: `rustc 1.69.0 (84c898d65 2023-04-16)`
 - `cargo generate --version`: `cargo generate-generate 0.18.2`

**Additional context**
I need empty values to write `.liquid` files that have `{% if PLACEHOLDER != "" %}` like the following example.

```liquid
[profile.release]
codegen-units = 1
lto = true
{%- if panic != "" %}
panic = "{{panic}}"
{%- endif %}
{%- if strip != "" %}
strip = "{{strip}}"
{%- endif %}

{%- if command != "" %}
[[bin]]
path = "src/main.rs"
name = "{{command}}"
{%- endif %}
```

**Comment by sassman** [comment]
@mamekoro That's a valid bug. Besides, just wondering what stops you from using the `default = ""` value in the placeholder definition? Then you could spare the `--define command`.

**Comment by mamekoro** [comment]
I guess I forgot about `default = ""` when I reported the issue. Thanks for #1078 though.
