### ISSUE TITLE
This tool is really great

### ISSUE THREAD

**Issue by hube12** [cargo-generate/cargo-generate#968]
I love the new features with rhai, it makes scripting so much more awesome, for instance here is my take on a full rust template https://github.com/hube12/template_rs

A few key features I like:
- The select between choice in terminal is really great (albeit powershell support is lacking)
```rust
variable::prompt("Text", "default", ["option1", "option2"]);
```
- The fact you can expand the date to the current with liquid is refreshing
```rust
{{ "now" | date: "%Y" }}
```
- Some of the variables being pass down like authors which allow to insert it easyly

Overall a feature packed tool

**Comment by sassman** [comment]
Thanks for the nice feedback.
If you feel any feature missing feel free to drop an issue.
