### ISSUE TITLE
[Mac OS] dyld[6431]: Library not loaded: libz.1.dylib

### ISSUE THREAD

**Issue by OscarTHZhang** [cargo-generate/cargo-generate#979]
**Describe the bug**
I am running Mac OS Ventura 13.4.1 with Apple M1 and try to generate a wasm-pack-template

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [x] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
2. output it generated..
```
dyld[6431]: Library not loaded: libz.1.dylib
  Referenced from: <1B48086C-1B69-3D08-93F3-EED42AF0A96A> /Users/Oscar/.cargo/bin/cargo-generate
  Reason: tried: 'libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibz.1.dylib' (no such file), 'libz.1.dylib' (no such file), '/Users/Oscar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libz.1.dylib' (no such file), '/Users/Oscar/anaconda/lib//libz.1.dylib' (no such file), '/Users/Oscar/anaconda/lib//libz.1.dylib' (no such file), '/libz.1.dylib' (no such file), '/Users/Oscar/Projects/libz.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Oscar/Projects/libz.1.dylib' (no such file), '/Users/Oscar/Projects/libz.1.dylib' (no such file), '/Users/Oscar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libz.1.dylib' (no such file), '/Users/Oscar/anaconda/lib//libz.1.dylib' (no such file), '/Users/Oscar/anaconda/lib//libz.1.dylib' (no such file), '/libz.1.dylib' (no such file)
[1]    6431 abort      cargo generate --git https://github.com/rustwasm/wasm-pack-template
```
3. See error

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.4.1 (22F82)
 - Build tools: gnu/gcc
 - Shell: zsh
 - `rustc --version`: rustc 1.70.0 (90c541806 2023-05-31)
 - `cargo generate --version`: unkonwn (`dyld[6610]: Library not loaded: libz.1.dylib`)

**Additional context**

**Comment by sassman** [comment]
could you pls try to do either:

1. make sure you have zlib and bzip2 installed: `brew install zlib bzip2`
2. reinstall libzip `brew reinstall --verbose libzip`

After that try to reinstall `cargo generate` you may try the `--locked` parameter on cargo install.

**Comment by OscarTHZhang** [comment]
I do have them installed. I was able to hack around and found the libz.1dylib and copied the file into the directory that I am running cargo-generate commands and that worked. But I know this is not the right way to do it

**Comment by OscarTHZhang** [comment]
@sassman I also tried your suggestion to reinstall `libzip` and reinstall `cargo generate`, but unfortunately that didn't work
