### ISSUE TITLE
no content-type header in response

### ISSUE THREAD

**Issue by stappersg** [cargo-generate/cargo-generate#988]
**Describe the bug**

Encountering an odd error message.
There is a valid _git clone URL_  but `cargo-generate` chokes on it.

**Stating**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [ ] `.gitconfig`  (not applicable)

**To Reproduce**
```text
export GIT_CLONE_URL=http://stappers.it/git/cargo-generate
cargo generate --git ${GIT_CLONE_URL} --name foo --verbose
```

Verbose version, shows that the URL is correct and shows the odd error:

```text
stappers@juli:/tmp
$ export GIT_CLONE_URL=http://stappers.it/git/cargo-generate
stappers@juli:/tmp
$ echo ${GIT_CLONE_URL}
http://stappers.it/git/cargo-generate
stappers@juli:/tmp
$ git clone ${GIT_CLONE_URL}
Cloning into 'cargo-generate'...
Fetching objects: 4065, done.
stappers@juli:/tmp
$ rm -rf cargo-generate/
stappers@juli:/tmp
$ cargo generate --git ${GIT_CLONE_URL} --name foo --verbose
Error: Please check if the Git user / repository exists.

Caused by:
    no content-type header in response; class=Http (34)
stappers@juli:/tmp
$ cargo generate --version
cargo generate-generate 0.18.3
stappers@juli:/tmp
$
```

**Expected behavior**
A succesfull `cargo generate` action like
```text
stappers@rosa:/tmp
$ cargo generate  --git /srv/git/cargo-generate --name foo --verbose
? 🤷   Which template should be expanded? ›
❯ example-templates/hooks
  example-templates/liquid-rhai-bridge
  example-templates/placeholders
```

**Additional context**

Is it a _HTTP thingy_?

**Comment by sassman** [comment]
Cargo generate as same as cargo uses libgit2 for cloning.
There I found the [following comment](https://github.com/libgit2/libgit2/issues/4844#issuecomment-428544005)

> The Accept header field here is application/x-git-upload-pack-result which is what you get when the server sends the packfile. However, glitch's implementation is sending Content-Type: application/x-git-upload-pack-advertisement which is neither what we asked for nor what it's delivering.

I'm not entirely sure if that information is still accurate, but your particular git server does not send the mentioned http header back, only this:

```raw
22:55:26.200489 http.c:664              == Info: Connected to stappers.it (2a01:7c8:aaae:103::1) port 80 (#2)
22:55:26.200566 http.c:611              => Send header, 0000000194 bytes (0x000000c2)
22:55:26.200572 http.c:623              => Send header: GET /git/cargo-generate/objects/info/packs HTTP/1.1
22:55:26.200576 http.c:623              => Send header: Host: stappers.it
22:55:26.200578 http.c:623              => Send header: User-Agent: git/2.34.1
22:55:26.200581 http.c:623              => Send header: Accept: */*
22:55:26.200583 http.c:623              => Send header: Accept-Encoding: deflate, gzip
22:55:26.200586 http.c:623              => Send header: Accept-Language: en-GB, *;q=0.9
22:55:26.200588 http.c:623              => Send header: Pragma: no-cache
22:55:26.200590 http.c:623              => Send header:
```
(see `GIT_CURL_VERBOSE=1 git clone http://stappers.it/git/cargo-generate foo`)

So I'd say this is an issue of libgit2 and I bet they would appreciate your issue report there, maybe it's a good idea to refer to their closed issue https://github.com/libgit2/libgit2/issues/4844 as well.

**Comment by stappersg** [comment]
Acknowledge

* Reported upstream
* This issue retitled with text from the underlaying library
* Taking label **waiting-for-user-input** as _"report back when you get information from upstream"_

**Comment by stappersg** [comment]
> Taking label **waiting-for-user-input** as _"report back when you get information from upstream"_

Edward Thomson, from  the `libgit2` project, asked for elaboration on the issue.
[Such information has been provided.](https://github.com/libgit2/libgit2/issues/6609#issuecomment-1675945885)

![Label waiting-for-user-input is removed](https://github.com/cargo-generate/cargo-generate/assets/35434094/ff20e70f-446f-42f2-93b3-5bf4c25c98ba)

**Comment by stappersg** [comment]
> **Additional context**
> 
> Is it a _HTTP thingy_?

[Yes](https://www.git-scm.com/docs/http-protocol)

**Comment by stappersg** [comment]
https://www.git-scm.com/docs/http-protocol

> **Additional context**
> 
> Is it a _HTTP thingy_?

[Yes](https://www.git-scm.com/docs/http-protocol)
